### ISSUE TITLE
在准备数据集task=9时，报错找不到track_params.pt

### ISSUE THREAD

**Issue by ZJ-CAI** [yerfor/GeneFace#100]
按照task从1~9的顺序，一步步执行，到了task=9的时候，报错说找不到track_params.pt

请问一定得按照peocess_data.sh中task的顺序来运行process.py吗？

[INFO] ===== save transforms =====
Traceback (most recent call last):
  File "/czj/GeneFace/data_util/process.py", line 448, in <module>
    save_transforms(processed_dir, ori_imgs_dir)
  File "/czj/GeneFace/data_util/process.py", line 296, in save_transforms
    params_dict = torch.load(os.path.join(base_dir, 'track_params.pt'))
  File "/root/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/train_final/track_params.pt'

**Comment by yerfor** [comment]
track_params.pt是处理face_tracking过程得到的结果，请运行对应步骤观察程序是否有报错。

不一定严格按照process_data.sh的流程。
