### ISSUE TITLE
FileNotFoundError: data/processed/videos/May/ori_imgs/0.lms not found.

### ISSUE THREAD

**Issue by rjc7011855** [yerfor/GeneFace#112]
你好，当我根据您的文档train_models.md运行时bash scripts/infer_lm3d_radnerf.sh 时，报错
Traceback (most recent call last):
  File "/mnt/shujupan/rjc/code/GeneFace/inference/nerfs/lm3d_radnerf_infer.py", line 99, in <module>
    LM3d_RADNeRFInfer.example_run(inp)
  File "/mnt/shujupan/rjc/code/GeneFace/inference/nerfs/base_nerf_infer.py", line 299, in example_run
    infer_ins = cls(hp)
  File "/mnt/shujupan/rjc/code/GeneFace/inference/nerfs/lm3d_radnerf_infer.py", line 15, in __init__
    self.dataset = self.dataset_cls('trainval', training=False)
  File "/mnt/shujupan/rjc/code/GeneFace/tasks/radnerfs/dataset_utils.py", line 104, in __init__
    lms = np.loadtxt(os.path.join(hparams['processed_data_dir'],hparams['video_id'], 'ori_imgs', str(img_id) + '.lms')) # [68, 2]
  File "/root/anaconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1301, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/root/anaconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/npyio.py", line 955, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/root/anaconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/root/anaconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: data/processed/videos/May/ori_imgs/0.lms not found.
可在之前的过程中，没发现生成data/processed/videos/May/ori_imgs的这个步骤，请问是我哪里有遗漏吗，感谢！

**Comment by yerfor** [comment]
可能是process_data.sh的前几个步骤出错了。lms没有正常生成的话应该是face_alignment模块提取人脸关键点出了问题。我猜测是因为这个提取模块需要从网上下载预训练模型，而国内下载模型经常中途失败。你可以多试几次或者尝试翻墙解决网络问题。

**Comment by tommysnu** [comment]
During running the process_data.sh I get the error.
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/transforms_train.json'
Can you help me fix this bug?

**Comment by JoshonSmith** [comment]
> During running the process_data.sh I get the error. FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/transforms_train.json' Can you help me fix this bug?

hi~
how did you fix the problem?
