### ISSUE TITLE
FileNotFoundError: data/processed/videos/May/ori_imgs/0.lms not found.

### ISSUE THREAD

**Issue by backclog** [yerfor/GeneFace#129]
HI, I encountered the following problem running `bash scripts/infer_lm3d_radnerf.sh` in `read me`

```
Traceback (most recent call last):
  File "/home/gom/GeneFace-main/inference/nerfs/lm3d_radnerf_infer.py", line 99, in <module>
    LM3d_RADNeRFInfer.example_run(inp)
  File "/home/gom/GeneFace-main/inference/nerfs/base_nerf_infer.py", line 299, in example_run
    infer_ins = cls(hp)
  File "/home/gom/GeneFace-main/inference/nerfs/lm3d_radnerf_infer.py", line 15, in __init__
    self.dataset = self.dataset_cls('trainval', training=False)
  File "/home/gom/GeneFace-main/tasks/radnerfs/dataset_utils.py", line 104, in __init__
    lms = np.loadtxt(os.path.join(hparams['processed_data_dir'],hparams['video_id'], 'ori_imgs', str(img_id) + '.lms')) # [68, 2]
  File "/root/anaconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1338, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/root/anaconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/root/anaconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/root/anaconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: data/processed/videos/May/ori_imgs/0.lms not found.

```
https://github.com/yerfor/GeneFace/issues/112#issuecomment-1515827892

I've seen answers to the same question on this issue, but I didn't quite understand the answer.
Please let me know a specific solution to this problem. Thank you.

**Comment by jessicawu11** [comment]
同样的问题，重新下载模型也不管用，应该不是模型的问题

**Comment by Alpacolypse** [comment]
Is there a fix for this?
