### ISSUE TITLE
執行CUDA_VISIBLE_DEVICES=0 python deep_3drecon/test.py 出現error

### ISSUE THREAD

**Issue by jerry4308** [yerfor/GeneFace#133]
error 訊息:
Traceback (most recent call last):
  File "/home/GeneFace/deep_3drecon/test.py", line 68, in <module>
    main(0, opt, 'deep_3drecon/datasets/examples')
  File "/home/GeneFace/deep_3drecon/test.py", line 52, in main
    im_tensor, lm_tensor = read_data(im_path[i], lm_path[i], lm3d_std)
  File "/home/GeneFace/deep_3drecon/test.py", line 27, in read_data
    _, im, lm, _ = align_img(im, lm, lm3d_std)
  File "/home/GeneFace/deep_3drecon/util/preprocess.py", line 204, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

請問一下，這個問題該如何處理呢? 是我那個步驟有出錯嗎?  謝謝~

**Comment by jerry4308** [comment]
後來我發現把出錯那行裡面所提的那5個變數，全部轉型成為int資料型態就可以了，已解決!

**Comment by Parikshat1998** [comment]
@jerry4308 How did you resolve it, can you please explain

**Comment by jerry4308** [comment]
w0, h0, s, t[0], t[1]

I remember I just changed the type of the above variables as the same type.

^^

**Comment by feifeitu1** [comment]
请问是在哪一步转换的呢，为什么我直接转换了还是报这个错？

**Comment by skrudrjs** [comment]
try this code

trans_params = np.array([w0, h0, s, t[0][0], t[1][0]])

**Comment by feifeitu1** [comment]
好的，谢谢~

**Comment by xiao-keeplearning** [comment]
Why this bug author has not fixed so far

**Comment by Pythonpa** [comment]
> try this code
> 
> trans_params = np.array([w0, h0, s, t[0][0], t[1][0]])

YES,this method works very well.
