### ISSUE TITLE
load模型的时候 总是出错，求助~CUDA_VISIBLE_DEVICES=0 data_gen/nerf/process_data.sh $VIDEO_ID

### ISSUE THREAD

**Issue by MoroseYu** [yerfor/GeneFace#138]
[INFO] ===== save transforms =====
[INFO] ===== finished saving transforms =====
Loading the Wav2Vec2 Processor...
Downloading (…)rocessor_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 212/212 [00:00<00:00, 18.1kB/s]
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 138/138 [00:00<00:00, 12.1kB/s]
Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.38k/1.38k [00:00<00:00, 586kB/s]
Downloading (…)olve/main/vocab.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 291/291 [00:00<00:00, 115kB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 85.0/85.0 [00:00<00:00, 31.4kB/s]
Loading the HuBERT Model...
Traceback (most recent call last):
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/work/GeneFace-main/data_gen/nerf/extract_hubert_mel_f0.py", line 5, in <module>
    from data_gen.process_lrs3.process_audio_hubert import get_hubert_from_16k_speech
  File "/home/test/work/GeneFace-main/data_gen/process_lrs3/process_audio_hubert.py", line 9, in <module>
    hubert_model = HubertModel.from_pretrained("facebook/hubert-large-ls960-ft")
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2091, in from_pretrained
    resolved_archive_file = cached_file(pretrained_model_name_or_path, filename, **cached_file_kwargs)
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1364, in hf_hub_download
    http_get(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 505, in http_get
    r = _request_wrapper(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 442, in _request_wrapper
    return http_backoff(
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 212, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/test/anaconda3/envs/geneface/lib/python3.9/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
loading the model from deep_3drecon/checkpoints/facerecon/epoch_20.pth
loading video ...
extracting 2D facial landmarks ...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6073/6073 [06:58<00:00, 14.50it/s]

其他模型貌似都可以正常load，求助大家~

**Comment by shengzewen** [comment]
我也出现这种错误兄弟，你是怎么解决的

**Comment by stevetatum** [comment]
我也是这种错误，请问你解决了吗
