### ISSUE TITLE
同样的环境跑radnerf没问题，但是geneface报错FileNotFoundError: data/processed/videos/May/ori_imgs/0.lms not found.

### ISSUE THREAD

**Issue by jessicawu11** [yerfor/GeneFace#142]
Traceback (most recent call last):
  File "inference/nerfs/lm3d_radnerf_infer.py", line 99, in <module>
    LM3d_RADNeRFInfer.example_run(inp)
  File "/root/GeneFace/inference/nerfs/base_nerf_infer.py", line 299, in example_run
    infer_ins = cls(hp)
  File "inference/nerfs/lm3d_radnerf_infer.py", line 15, in __init__
    self.dataset = self.dataset_cls('trainval', training=False)
  File "/root/GeneFace/tasks/radnerfs/dataset_utils.py", line 104, in __init__
    lms = np.loadtxt(os.path.join(hparams['processed_data_dir'],hparams['video_id'], 'ori_imgs', str(img_id) + '.lms')) # [68, 2]
  File "/root/anaconda3/envs/rad/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1042, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/root/anaconda3/envs/rad/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/root/anaconda3/envs/rad/lib/python3.8/site-packages/numpy/lib/_datasource.py", line 532, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: data/processed/videos/May/ori_imgs/0.lms not found.

**Comment by yerfor** [comment]
Hi，看起来是face_alignment提取landmark的过程出了bug，导致lms没有被正常提取。
