### ISSUE TITLE
显存占满，GPU使用率为0

### ISSUE THREAD

**Issue by ioneday** [yerfor/GeneFace#148]
在运行 `bash scripts/infer_lm3d_radnerf.sh` 时，报显存不足的错误

观察GPU占用情况：
- 4090-24G显存占满
- GPU使用率为0
- 且无其他进程占用GPU

`(geneface) root@autodl-container-d31d468cfc-1df6d0ae:~/autodl-tmp/GeneFace# bash scripts/infer_lm3d_radnerf.sh
| Unknow hparams:  []
| Hparams chains:  ['egs/egs_bases/radnerf/base.yaml', 'egs/egs_bases/radnerf/lm3d_radnerf.yaml', 'checkpoints/xiaoquan/lm3d_radnerf_torso/config.yaml']
| Hparams: 
accumulate_grad_batches: 1, ambient_out_dim: 2, amp: True, base_config: ['egs/egs_bases/radnerf/lm3d_radnerf.yaml'], binary_data_dir: data/binary/videos, 
bound: 1, camera_offset: [0, 0, 0], camera_scale: 4.0, clip_grad_norm: 0, clip_grad_value: 0, 
cond_out_dim: 64, cond_type: idexp_lm3d_normalized, cond_win_size: 1, cuda_ray: True, debug: False, 
density_thresh: 10, density_thresh_torso: 0.01, desired_resolution: 2048, dt_gamma: 0.00390625, eval_max_batches: 100, 
exp_name: , far: 0.9, finetune_lips: True, finetune_lips_start_iter: 200000, geo_feat_dim: 128, 
grid_interpolation_type: linear, grid_size: 128, grid_type: tiledgrid, gui_fovy: 21.24, gui_h: 512, 
gui_max_spp: 1, gui_radius: 3.35, gui_w: 512, head_model_dir: checkpoints/xiaoquan/lm3d_radnerf, hidden_dim_ambient: 128, 
hidden_dim_color: 128, hidden_dim_sigma: 128, individual_embedding_dim: 4, individual_embedding_num: 13000, infer: True, 
infer_audio_source_name: data/raw/val_wavs/kexue.wav, infer_bg_img_fname: , infer_c2w_name: , infer_cond_name: infer_out/xiaoquan/pred_lm3d/kexue.npy, infer_lm3d_clamp_std: 2.5, 
infer_lm3d_lle_percent: 0.0, infer_lm3d_smooth_sigma: 0.0, infer_out_video_name: infer_out/xiaoquan/pred_video/kexue_radnerf_torso_smo.mp4, infer_scale_factor: 1.0, infer_smo_std: 0.0, 
infer_smooth_camera_path: True, infer_smooth_camera_path_kernel_size: 7, lambda_ambient: 0.1, lambda_lpips_loss: 0.01, lambda_weights_entropy: 0.0001, 
load_ckpt: , load_imgs_to_memory: False, log2_hashmap_size: 16, lr: 0.0005, max_ray_batch: 4096, 
max_steps: 16, max_updates: 250000, min_near: 0.05, n_rays: 65536, near: 0.3, 
num_ckpt_keep: 1, num_layers_ambient: 3, num_layers_color: 2, num_layers_sigma: 3, num_sanity_val_steps: 2, 
num_steps: 16, num_valid_plots: 5, optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.999, print_nan_grads: False, 
processed_data_dir: data/processed/videos, raw_data_dir: data/raw/videos, resume_from_checkpoint: 0, save_best: True, save_codes: ['tasks', 'modules', 'egs'], 
save_gt: True, scheduler: exponential, seed: 9999, smo_win_size: 5, smooth_lips: False, 
task_cls: tasks.radnerfs.radnerf_torso.RADNeRFTorsoTask, tb_log_interval: 100, torso_head_aware: False, torso_individual_embedding_dim: 8, torso_shrink: 0.8, 
torso_train_mode: 1, update_extra_interval: 16, upsample_steps: 0, use_window_cond: True, val_check_interval: 2000, 
valid_infer_interval: 10000, valid_monitor_key: val_loss, valid_monitor_mode: min, validate: False, video_id: xiaoquan, 
warmup_updates: 0, weight_decay: 0, with_att: True, work_dir: checkpoints/xiaoquan/lm3d_radnerf_torso, 
2023-06-12 10:45:42.082337: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-12 10:45:42.129990: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-12 10:45:43.134897: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
06/12 10:45:43 AM GPU available: True, GPU used: [0]
trainval: Smooth head trajectory (rotation and translation) with a window size of 7
Saved 16khz wav file to data/raw/val_wavs/kexue_16k.wav.
Loaded pre-extracted 3D landmark sequence from infer_out/xiaoquan/pred_lm3d/kexue.npy!
| Unknow hparams:  []
Traceback (most recent call last):
  File "/root/autodl-tmp/GeneFace/inference/nerfs/lm3d_radnerf_infer.py", line 99, in <module>
    LM3d_RADNeRFInfer.example_run(inp)
  File "/root/autodl-tmp/GeneFace/inference/nerfs/base_nerf_infer.py", line 300, in example_run
    infer_ins.infer_once(inp)
  File "/root/autodl-tmp/GeneFace/inference/nerfs/base_nerf_infer.py", line 265, in infer_once
    batches = self.get_pose_from_ds(samples)
  File "/root/autodl-tmp/GeneFace/inference/nerfs/lm3d_radnerf_infer.py", line 23, in get_pose_from_ds
    ds_sample = self.dataset[i]
  File "/root/autodl-tmp/GeneFace/tasks/radnerfs/dataset_utils.py", line 178, in __getitem__
    rays = get_rays(ngp_pose.cuda(), self.intrinsics, self.H, self.W, N=-1)
  File "/root/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/autodl-tmp/GeneFace/modules/radnerfs/utils.py", line 355, in get_rays
    directions = directions / torch.norm(directions, dim=-1, keepdim=True)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB (GPU 0; 23.65 GiB total capacity; 20.23 GiB already allocated; 8.56 MiB free; 22.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by ioneday** [comment]
我发现用 `Wav_ID=zozo` 这个音频就没问题，但换成自己的音频就报错了

**Comment by ioneday** [comment]
问题解决了

原音频时长1分30多秒，修剪至1分钟以内，就没问题了。
