### ISSUE TITLE
处理 May.mp4 报错

### ISSUE THREAD

**Issue by crazySyaoran** [yerfor/GeneFace#149]
Hi 我按照 [process_target_person_video-zh.md](https://github.com/yerfor/GeneFace/blob/main/docs/process_data/zh/process_target_person_video-zh.md) 运行 `data_gen/nerf/process_data.sh` 

运行到

```
# 5. save head, torso, gt imgs
python data_util/process.py --video_id=$1 --task=6
```

报了`No such file or directory`的错误，请问是为什么呢？以下是报错信息，谢谢~

```
[INFO] ===== save transforms =====
Traceback (most recent call last):
  File "/home/ubuntu/GeneFace/data_util/process.py", line 446, in <module>
    save_transforms(processed_dir, ori_imgs_dir)
  File "/home/ubuntu/GeneFace/data_util/process.py", line 294, in save_transforms
    params_dict = torch.load(os.path.join(base_dir, 'track_params.pt'))
  File "/home/ubuntu/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ubuntu/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ubuntu/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/track_params.pt'
Loading the Wav2Vec2 Processor...
Loading the HuBERT Model...
Some weights of the model checkpoint at facebook/hubert-large-ls960-ft were not used when initializing HubertModel: ['lm_head.bias', 'lm_head.weight']
- This IS expected if you are initializing HubertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing HubertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2023-06-14 09:22:50.227646: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-14 09:22:51.107196: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Hubert extracted at data/processed/videos/May/aud_hubert.npy
Mel and F0 extracted at data/processed/videos/May/aud_mel_f0.npy
Traceback (most recent call last):
  File "/home/ubuntu/GeneFace/data_gen/nerf/extract_3dmm.py", line 16, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, network_size=4, device='cuda')
  File "/home/ubuntu/miniconda3/envs/geneface/lib/python3.9/enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D
| Unknow hparams:  []
| Hparams chains:  ['egs/egs_bases/radnerf/base.yaml', 'egs/egs_bases/radnerf/lm3d_radnerf.yaml', 'egs/datasets/videos/May/lm3d_radnerf.yaml']
| Hparams:
accumulate_grad_batches: 1, ambient_out_dim: 2, amp: True, base_config: ['egs/egs_bases/radnerf/lm3d_radnerf.yaml'], binary_data_dir: data/binary/videos,
bound: 1, camera_offset: [0, 0, 0], camera_scale: 4.0, clip_grad_norm: 0, clip_grad_value: 0,
cond_out_dim: 64, cond_type: idexp_lm3d_normalized, cond_win_size: 1, cuda_ray: True, debug: False,
density_thresh: 10, density_thresh_torso: 0.01, desired_resolution: 2048, dt_gamma: 0.00390625, eval_max_batches: 100,
exp_name: , far: 0.9, finetune_lips: True, finetune_lips_start_iter: 200000, geo_feat_dim: 128,
grid_interpolation_type: linear, grid_size: 128, grid_type: tiledgrid, gui_fovy: 21.24, gui_h: 512,
gui_max_spp: 1, gui_radius: 3.35, gui_w: 512, hidden_dim_ambient: 128, hidden_dim_color: 128,
hidden_dim_sigma: 128, individual_embedding_dim: 4, individual_embedding_num: 13000, infer: False, infer_audio_source_name: ,
infer_bg_img_fname: , infer_c2w_name: , infer_cond_name: , infer_lm3d_clamp_std: 2.5, infer_lm3d_lle_percent: 0.0,
infer_lm3d_smooth_sigma: 0.0, infer_out_video_name: , infer_scale_factor: 1.0, infer_smo_std: 0.0, infer_smooth_camera_path: True,
infer_smooth_camera_path_kernel_size: 7, lambda_ambient: 0.1, lambda_lpips_loss: 0.01, lambda_weights_entropy: 0.0001, load_ckpt: ,
load_imgs_to_memory: False, log2_hashmap_size: 16, lr: 0.0005, max_ray_batch: 4096, max_steps: 16,
max_updates: 250000, min_near: 0.05, n_rays: 65536, near: 0.3, num_ckpt_keep: 1,
num_layers_ambient: 3, num_layers_color: 2, num_layers_sigma: 3, num_sanity_val_steps: 2, num_steps: 16,
num_valid_plots: 5, optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.999, print_nan_grads: False, processed_data_dir: data/processed/videos,
raw_data_dir: data/raw/videos, resume_from_checkpoint: 0, save_best: True, save_codes: ['tasks', 'modules', 'egs'], save_gt: True,
scheduler: exponential, seed: 9999, smo_win_size: 5, smooth_lips: False, task_cls: tasks.radnerfs.radnerf.RADNeRFTask,
tb_log_interval: 100, torso_head_aware: False, torso_individual_embedding_dim: 8, torso_shrink: 0.8, update_extra_interval: 16,
upsample_steps: 0, use_window_cond: True, val_check_interval: 2000, valid_infer_interval: 10000, valid_monitor_key: val_loss,
valid_monitor_mode: min, validate: False, video_id: May, warmup_updates: 0, weight_decay: 0,
with_att: True, work_dir: ,
loading deepspeech ...
loading Esperanto ...
loading hubert ...
loading Mel and F0 ...
loading 3dmm coeff ...
Traceback (most recent call last):
  File "/home/ubuntu/GeneFace/data_gen/nerf/binarizer.py", line 277, in <module>
    binarizer.parse(hparams['video_id'])
  File "/home/ubuntu/GeneFace/data_gen/nerf/binarizer.py", line 267, in parse
    ret = load_processed_data(processed_dir)
  File "/home/ubuntu/GeneFace/data_gen/nerf/binarizer.py", line 98, in load_processed_data
    coeff_dict = np.load(coeff_npy_name, allow_pickle=True).tolist()
  File "/home/ubuntu/miniconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/vid_coeff.npy'
```

**Comment by yerfor** [comment]
Hi, 'data/processed/videos/May/vid_coeff.npy' not found denotes that the extracting 3DMM process has failed. Maybe you could run the commands in `process.sh` step by step.

**Comment by crazySyaoran** [comment]
modify `/GeneFace/data_util/process.py, line 55`
```
fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)
```
to
```
fa = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, flip_input=False)
```

then the error message gone.

**Comment by maurizio-kodelab** [comment]
Thank you.
I applied same fix to the file /GeneFace/data_gen/nerf/extract_3dmm.py too.

Best regards

On 15 Jun 2023, at 10:28, Juncheng ***@***.***> wrote:



modify /GeneFace/data_util/process.py, line 55

fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)


to

fa = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, flip_input=False)


then the error message gone.

**Comment by marsjin** [comment]
data_util/ process.py
data_gen/nerf/extract_3dmm.py
都需要修改 _2D 为 TWO_D
