### ISSUE TITLE
训练postnet模型报错

### ISSUE THREAD

**Issue by helen5106** [yerfor/GeneFace#159]
```python
(geneface) E:\Python_Program\GeneFace>python tasks/run.py --config=egs/datasets/videos/May/lm3d_postnet_sync.yaml --exp_name=May/postnet
| Unknow hparams:  []
Namespace(config='egs/datasets/videos/May/lm3d_postnet_sync.yaml', exp_name='May/postnet', hparams='', infer=False, validate=False, reset=False, remove=False, debug=False)
| Hparams chains:  ['egs\\egs_bases\\audio2motion\\base.yaml', 'egs/egs_bases/audio2motion/vae_sync.yaml', 'egs/egs_bases/postnet/base.yaml', 'egs/datasets/videos/May/lm3d_postnet_sync.yaml']
| Hparams:
accumulate_grad_batches: 1, amp: False, audio2motion_ckpt_steps: 40000, audio2motion_task_cls: tasks.audio2motion.lm3d_vae_sync.VAESyncAudio2MotionTask, audio2motion_work_dir: checkpoints/lrs3/lm3d_vae_sync/,
base_config: ['egs/egs_bases/postnet/base.yaml'], binary_data_dir: data/binary/lrs3, clip_grad_norm: 1, clip_grad_value: 0, debug: False,
discriminator_scheduler_params: {'gamma': 0.5, 'step_size': 40000}, eval_max_batches: 10, exp_name: May/postnet, gen_dir_name: , hidden_size: 256,
infer: False, infer_audio_source_name: data/raw/val_wavs/zozo.wav, infer_ckpt_steps: 6000, infer_out_npy_name: infer_out/May/pred_lm3d/zozo.npy, lambda_kl: 0.5,
load_ckpt: , load_db_to_memory: True, lr: 0.0005, max_updates: 20000, num_ckpt_keep: 500,
num_sanity_val_steps: 5, num_valid_plots: 1, optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.999, person_binary_data_dir: data/binary/videos,
postnet_disc_interval: 1, postnet_disc_lr: 0.0001, postnet_disc_start_steps: 0, postnet_lambda_adv: 0.85, postnet_lambda_mse: 0.05,
postnet_lambda_sync: 0.1, postnet_lr: 0.0001, print_nan_grads: False, resume_from_checkpoint: 0, save_best: False,
save_codes: ['tasks', 'modules', 'egs'], save_gt: True, scheduler: none, seed: 9999, syncnet_ckpt_steps: 40000,
syncnet_work_dir: checkpoints/lrs3/syncnet, task_cls: tasks.postnet.lm3d_postnet_adv_sync.PostnetAdvSyncTask, tb_log_interval: 100, val_check_interval: 1000, valid_infer_interval: 1000,
valid_monitor_key: val_loss, valid_monitor_mode: min, validate: False, video_id: May, warmup_updates: 1000,
weight_decay: 0, work_dir: checkpoints/May/postnet,
06/28 01:26:12 PM GPU available: True, GPU used: [0]
| model Arch:  LandmarkHubertSyncNet(
  (hubert_encoder): Sequential(
    (0): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(1024, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (1): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (2): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (3): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (4): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 256, kernel_size=(3,), stride=(2,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (5): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (6): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (7): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 512, kernel_size=(3,), stride=(2,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (8): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (9): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (10): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (11): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (12): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(1,), stride=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
  )
  (mouth_encoder): Sequential(
    (0): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(60, 96, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (1): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(96, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (2): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (3): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (4): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 256, kernel_size=(3,), stride=(2,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (5): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (6): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (7): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (8): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (9): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (10): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (11): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (12): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(1,), stride=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
  )
  (logloss): BCELoss()
)
| model Trainable Parameters: 9.304M
| load 'model' from 'checkpoints/lrs3/syncnet/model_ckpt_steps_40000.ckpt'.
| load 'model' from 'checkpoints/lrs3/lm3d_vae_sync//model_ckpt_steps_40000.ckpt'.
| model Arch:  LandmarkHubertSyncNet(
  (hubert_encoder): Sequential(
    (0): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(1024, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (1): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (2): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (3): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (4): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 256, kernel_size=(3,), stride=(2,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (5): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (6): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (7): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 512, kernel_size=(3,), stride=(2,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (8): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (9): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (10): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (11): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (12): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(1,), stride=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
  )
  (mouth_encoder): Sequential(
    (0): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(60, 96, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (1): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(96, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (2): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (3): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (4): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 256, kernel_size=(3,), stride=(2,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (5): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (6): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (7): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (8): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (9): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (10): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (11): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(3,), stride=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
    (12): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(512, 512, kernel_size=(1,), stride=(1,))
        (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): ReLU()
    )
  )
  (logloss): BCELoss()
)
| model Trainable Parameters: 9.304M
| load 'model' from 'checkpoints/lrs3/syncnet/model_ckpt_steps_40000.ckpt'.
| Copied codes to checkpoints/May/postnet/codes/20230628132614.
| model Arch:  CNNPostNet(
  (block1): Sequential(
    (0): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(204, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (1): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (2): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): LeakyReLU(negative_slope=0.2, inplace=True)
    )
  )
  (block2): Sequential(
    (0): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(128, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (1): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (2): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 256, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): LeakyReLU(negative_slope=0.2, inplace=True)
    )
  )
  (block3): Sequential(
    (0): Conv1d(
      (conv_block): Sequential(
        (0): Conv1d(256, 128, kernel_size=(3,), stride=(1,), padding=(1,))
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (act): LeakyReLU(negative_slope=0.2, inplace=True)
    )
    (1): Conv1d(128, 204, kernel_size=(1,), stride=(1,))
  )
)
| model Trainable Parameters: 0.797M
Loading database to memory...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 296/296 [00:00<00:00, 799.44it/s]
Sanity Val:   0%|                                                                                                                                                                       | 0/5 [00:00<?, ?step/s]
Traceback (most recent call last):
  File "E:\Python_Program\GeneFace\tasks\run.py", line 19, in <module>
    run_task()
  File "E:\Python_Program\GeneFace\tasks\run.py", line 14, in run_task
    task_cls.start()
  File "E:\Python_Program\GeneFace\utils\commons\base_task.py", line 251, in start
    trainer.fit(cls)
  File "E:\Python_Program\GeneFace\utils\commons\trainer.py", line 122, in fit
    self.run_single_process(self.task)
  File "E:\Python_Program\GeneFace\utils\commons\trainer.py", line 186, in run_single_process
    self.train()
  File "E:\Python_Program\GeneFace\utils\commons\trainer.py", line 261, in train
    self.evaluate(self.task, False, 'Sanity Val', max_batches=self.num_sanity_val_steps)
  File "E:\Python_Program\GeneFace\utils\commons\trainer.py", line 223, in evaluate
    for batch_idx, batch in enumerate(pbar):
  File "E:\ProgramData\anaconda3\envs\geneface\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "E:\ProgramData\anaconda3\envs\geneface\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "E:\ProgramData\anaconda3\envs\geneface\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "E:\ProgramData\anaconda3\envs\geneface\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "E:\ProgramData\anaconda3\envs\geneface\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "E:\ProgramData\anaconda3\envs\geneface\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\ProgramData\anaconda3\envs\geneface\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "E:\ProgramData\anaconda3\envs\geneface\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\ProgramData\anaconda3\envs\geneface\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.BufferedReader' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\ProgramData\anaconda3\envs\geneface\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "E:\ProgramData\anaconda3\envs\geneface\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
``` 

Run this command:
python tasks/run.py --config=egs/datasets/videos/May/lm3d_postnet_sync.yaml --exp_name=May/postnet

**Comment by yfliao** [comment]
I am also stuck here but got a different error:

| model Trainable Parameters: 9.304M
checkpoints/lrs3/syncnet/model_ckpt_steps_40000.ckpt
Traceback (most recent call last):
  File "/usr1/liao/GeneFace/tasks/run.py", line 19, in <module>
    run_task()
  File "/usr1/liao/GeneFace/tasks/run.py", line 14, in run_task
    task_cls.start()
  File "/usr1/liao/GeneFace/utils/commons/base_task.py", line 251, in start
    trainer.fit(cls)
  File "/usr1/liao/GeneFace/utils/commons/trainer.py", line 120, in fit
    self.task = task_cls()
  File "/usr1/liao/GeneFace/tasks/postnet/lm3d_postnet_adv_sync.py", line 22, in __init__
    self.audio2motion_task = self.build_audio2motion_task()
  File "/usr1/liao/GeneFace/tasks/postnet/lm3d_postnet_adv_sync.py", line 34, in build_audio2motion_task
    self.audio2motion_task.build_model()
  File "/usr1/liao/GeneFace/tasks/audio2motion/lm3d_vae_sync.py", line 30, in build_model
    load_ckpt(self.syncnet_task.model, hparams["syncnet_work_dir"], steps=hparams["syncnet_ckpt_steps"])
  File "/usr1/liao/GeneFace/utils/commons/ckpt_utils.py", line 35, in load_ckpt
    checkpoint, ckpt_path = get_last_checkpoint(ckpt_base_dir, steps)
  File "/usr1/liao/GeneFace/utils/commons/ckpt_utils.py", line 14, in get_last_checkpoint
    checkpoint = torch.load(last_ckpt_path, map_location='cpu')
  File "/home/liao/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/liao/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: read(): fd 34 failed with Input/output error
