### ISSUE TITLE
训练postnet模型报错

### ISSUE THREAD

**Issue by more-strive** [yerfor/GeneFace#161]
1, 使用的命令是
```
CUDA_VISIBLE_DEVICES=0 python tasks/run.py --config=egs/datasets/videos/May/lm3d_postnet_sync.yaml --exp_name=May/postnet
```
2, May.mp4 换成了自己提供的视频，
![image](https://github.com/yerfor/GeneFace/assets/113762408/a179fe2a-ce4c-4cdb-b293-a1b3894ef1e2)

```
Loading database to memory...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 296/296 [00:00<00:00, 549.16it/s]
Sanity Val:  20%|████████████████████████████▏                                                                                                                | 1/5 [00:13<00:55, 13.95s/step]
| Validation results@0: {'total_loss': 0.2271, 'mse': 0.038, 'sync': 0.1892}
Loading database to memory...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28998/28998 [00:58<00:00, 497.64it/s]
0step [00:04, ?step/s]
Traceback (most recent call last):
  File "/root/.virtualenvs/geneface/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/queue.py", line 179, in get
    trainer.fit(cls)
  File "/mnt/d/GeneFace-main/utils/commons/trainer.py", line 122, in fit
    self.run_single_process(self.task)
  File "/mnt/d/GeneFace-main/utils/commons/trainer.py", line 186, in run_single_process
    self.train()
  File "/mnt/d/GeneFace-main/utils/commons/trainer.py", line 283, in train
    for batch_idx, batch in enumerate(train_pbar):
  File "/root/.virtualenvs/geneface/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/root/.virtualenvs/geneface/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/.virtualenvs/geneface/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/root/.virtualenvs/geneface/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "/root/.virtualenvs/geneface/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1145, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 8141) exited unexpectedly
```

**Comment by more-strive** [comment]
修改代码中所有的num_workers=4 改为num_workers=0，就可以了
