### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by WellTung666** [yerfor/GeneFace#163]
你好，我按照install_guide-zh.md安装环境并验证安装后，根据process_target_person_video-zh.md文件运行CUDA_VISIBLE_DEVICES=0 data_gen/nerf/process_data.sh $VIDEO_ID时出现这个错误，似乎是由transformers引起的，尝试更换版本并没有用。
![geneface_error](https://github.com/yerfor/GeneFace/assets/48502095/24ff6667-30a4-46b1-ae26-bb5e75f07ab0)

最后运行结束会出现FileNotFoundError: [Error 2 ] No such file or directory: 'data/processed/videos/May/vid_coeff.npy'错误，请问该如何解决呢？ 谢谢～

**Comment by jessicawu11** [comment]
同问，一样这个问题

**Comment by tailangjun** [comment]
我这边处理 Obama和 Obama2，提示
Traceback (most recent call last):
  File "/home/tailangjun/Documents/AIGenHuman/2DHuman/GeneFace/data_gen/nerf/binarizer.py", line 277, in <module>
    binarizer.parse(hparams['video_id'])
  File "/home/tailangjun/Documents/AIGenHuman/2DHuman/GeneFace/data_gen/nerf/binarizer.py", line 267, in parse
    ret = load_processed_data(processed_dir)
  File "/home/tailangjun/Documents/AIGenHuman/2DHuman/GeneFace/data_gen/nerf/binarizer.py", line 98, in load_processed_data
    coeff_dict = np.load(coeff_npy_name, allow_pickle=True).tolist()
  File "/opt/anaconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/Obama2/vid_coeff.npy'

**Comment by tailangjun** [comment]
我查了一下代码，vid_coeff.npy是第9步生成的，说明那一步执行失败了
9. calculate 3DMM 
python data_gen/nerf/extract_3dmm.py --video_id=$VIDEO_ID

我手动再执行一遍，会得到如下的错误
python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/opt/anaconda3/envs/geneface/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?

**Comment by tailangjun** [comment]
我知道问题了，pytorch3d对torch、torchversion的要求是非常奇葩的，完全没有按照PyTorch官网推荐的安装命令来（估计是 facebook的大佬就是不走寻常路），我们如果还用PyTorch官网推荐的安装命令来装，会出现各种奇葩事情，比方说

# 安装 torch
$  pip install torch==2.0.0+cu117 torchvision==0.15.1+cu117 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu117

# 安装 pytorch3d前
$ conda list | grep torch
torch                     2.0.0+cu117              pypi_0    pypi
torchaudio                2.0.1+cu117              pypi_0    pypi
torchvision               0.15.1+cu117             pypi_0    pypi

# 安装 pytorch3d，会修改 torch的版本，fuck。。。
conda install pytorch3d -c pytorch3d -y

# 安装 pytorch3d后
$ conda list | grep torch
pytorch3d                 0.7.4           py39_cu113_pyt1121    pytorch3d
torch                     2.0.0                    pypi_0    pypi
torchaudio                2.0.1+cu117              pypi_0    pypi
torchvision               0.15.1+cu117             pypi_0    pypi

注意 2.0.0+cu117 和 2.0.0不是一个东西

**Comment by tailangjun** [comment]
如果 pytorch3d是通过源码编译安装的，虽然不会改 torch的版本，但是又会导致 pytorch3d/pytorch3d/_C.cpython-39-x86_64-linux-gnu.so: undefined的错误。

安装命令
    rm -rf build/ **/*.so
    pip install -e .

所以这里的环境还是按照作者的来，不要修改任何版本信息。虽然版本比较老，和CUDA11.7+也不太搭，但跑起来生成 vid_coeff.npy是没问题的，凑活着用吧，Facebook估计也不会改了。。。

conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch

**Comment by tailangjun** [comment]
问题我搞清楚了，本质问题是 torch、torchversion、pytorch3d的版本不匹配
按照 pytorch3d官网的说法，目前仅仅支持这些情况

Linux or macOS or Windows
Python 3.8, 3.9 or 3.10
PyTorch 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 2.0.0 or 2.0.1.

具体的安装连接 https://github.com/facebookresearch/pytorch3d/issues/1401
