### ISSUE TITLE
running into this error when this script is run: CUDA_VISIBLE_DEVICES=0 /content/GeneFace/data_gen/nerf/process_data.sh $VIDEO_ID

### ISSUE THREAD

**Issue by VB1-VENOM** [yerfor/GeneFace#164]
FileNotFoundError: [Errno 2] No such file or directory: '/content/GeneFace/data_util/face_tracking/3DMM/3DMM_info.npy'

This is the full output:
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM dmix
[WARN] audio has 2 channels, only use the first.
[INFO] loaded audio stream data/processed/videos/May/aud.wav: (3886763,)
[INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto...
/usr/local/lib/python3.10/site-packages/transformers/configuration_utils.py:380: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
frame= 6073 fps=149 q=1.0 Lsize=N/A time=00:04:02.88 bitrate=N/A speed=5.96x    
video:287209kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[INFO] ===== extracted images =====
[INFO] ===== extract face landmarks from data/processed/videos/May/ori_imgs =====
2023-07-18 03:18:05.682469: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-18 03:18:06.952847: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
  0% 0/6073 [00:00<?, ?it/s][START]
 uniuje vizaĉanĝu de fl eĉo morispaas st antl ugehedt di opu ĉiu ni ĉhis ĝkam ant de ŝi evis aj kun sizuol tuanti sevtiin hasen stuo ajbli dajs ofu ĉiu ne ĉiezo kurajĉu da n eva fubuihevn eid amomentas ĉisiĵon an seŝ aŭ seŭ on niu du reĉon adi fto aĝis sekstii mu s la gia juvaŭ ĉi itu da ĉein ĝ disis li ea pisto tmekis hap on ajn a ud refuenĝo bla as ĉiunuvestiva jsi fertoajns an laŭov koosted no sevi bonŝeedz saj impunĝu viru oveŭ ŝi ten zajmuaj prajna ju ĉiuj sed azui feis liop ĉu neceza herbas aŭ ŝe dintro esc dam mpe ŝins kan prinos ĉi gata ui omon da sia buĉo nuĉis sronga da nati s tudeej voj omon te kamtu diris fe ra ce efri bon hasĉ ams de sukcii poj obon sne ŝundris sai fan sekio fraĉj udun ant kv ar ĉoron li sambe ŝun s ju najĉas se zobujoneŭ longa a da fefti ĉiuj p senĝo vaŭĝed li iv antofori aj psendu vaŭĉi ĝu neajn po buan k urei ĉiiunienof pipolundne ŝins udopra ud hisĝuj anto broi t fiuĉa se bonaj seĉ umanon gez sia iŝinĉejpo lenj oro pde ŝia etubi vui zaĉen mojn de nove ĉi raante r gedo roits dio noĝasbo deu sin faŭĉit li iv por f aevlui sen gupa s neniskanĉoj efko s drefremdo m la itpeazomfa d deveŝinsina a kan ĉoj pri neŭzue prosp urin anftaŭ izua not daizu ken isli baadaŭ lon hojm senta ĉ uron duo gradsku fajndas k io ĝoob antdeu suka nod en ŝo r dereso hima kan tribuecuel antdaŭispo hilm eĉ ĝas no t desisti gi ebiniĝ pol da an diis paroj a stas haŭurpi buba k si ki ujn la beto dieloĵ helmpa ornm i buakinpipo dvisaŭt objeĉululi gu naj cirpoĉan n en muĉboj a o junaeti de na sidisumŝipe vdis kurajtne jiŝon junajce ĝe ni op ĉiu neĉesa ĝa eŭpon ĉe o na pipo anĝj nojtis pajda princ ipo dris eŭnlio tal enĝen hor buir k da ĉu dit amen io fiuĉ a aftro ĝis u juna ĝidro ap ipol heva ĉiiv iĉ kraittengs s tro apraŝis juni el ovnei ŝins inglan s kotland ue osdnovan a lend tva junino pipo fron s po s deimstua mfo siespis naciistu ĉamo ĉe s skuustr o hospros anto pavo truagiu ni enov k omiuno ĉeis an fables erkoz zi ĝis ĝast peg gkloibolevanc ertu fajno jea ĝis l upers mufengs e todis av ĝi mapilgie ju sdonĉo fres ĝo bo pajo f est hajm en majpiz iĝe ejo ĉurin sta skulo ka ŭ ofte juniversĉ i ol juviĉoja afto laivĉajno haruerk vi stings laivs majo sĉems ado fing sot pajndas ĉiu evolui a asof anta asti keem pei ĝej koks tiu selĉaĝi li ĉajkenfumezl aosĝie puŝeĝ mi a famo junaiĉe d — anthaf amo lin komen donat uĉ ĉ divacas i ha v gaŭrnop ĉiune ĝi iĝu deamen strueitlad ĉu brinn is konĉuite gata a asnevo de fu sead o ĉ hu evo juao e evol u lev a l polo ĉeeksiko nu mi ensissoa ĉi buakf o jilu norĝaste pri veleĝi fien scuasmi lokehe tu jer voko ĉunzi and jiu nocei leĉmi buŝ iu ĝo famle apisvo l pros prs ant hapi ni ujea
[END]
[INFO] save all feats for training purpose... 
[INFO] saved logits to data/processed/videos/May/aud_esperanto.npy
[INFO] ===== extracted esperanto =====
[INFO] ===== extract deepspeech =====
2023-07-18 03:18:29.625639: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-18 03:18:30.957469: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
  0% 1/6073 [00:16<27:36:26, 16.37s/it]/root/.tensorflow/models/deepspeech-0_1_0-b90017e8.pb
2023-07-18 03:18:43.251959: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-18 03:18:43.297082: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-18 03:18:43.297441: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-18 03:18:43.298637: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-18 03:18:43.298938: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-18 03:18:43.299191: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-18 03:18:45.142715: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-18 03:18:45.143106: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-18 03:18:45.143380: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-18 03:18:45.143558: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2023-07-18 03:18:45.143613: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8274 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
tring to extract deepspeech from audio file:  data/processed/videos/May/aud.wav
The target is:  data/processed/videos/May/aud_deepspeech.npy
/content/GeneFace/data_util/deepspeech_features/deepspeech_features.py:50: UserWarning: Audio has multiple channels, the first channel is used
  warnings.warn(
2023-07-18 03:18:47.928052: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
2023-07-18 03:18:49.842635: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 201326592 exceeds 10% of free system memory.
2023-07-18 03:18:50.220718: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 201326592 exceeds 10% of free system memory.
2023-07-18 03:18:55.345393: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 201326592 exceeds 10% of free system memory.
2023-07-18 03:18:55.705536: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 201326592 exceeds 10% of free system memory.
2023-07-18 03:18:55.942950: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 201326592 exceeds 10% of free system memory.
  3% 167/6073 [01:02<09:08, 10.76it/s]Killed
[INFO] ===== extracted deepspeech =====
[INFO] ===== extracted all audio labels =====
100% 6073/6073 [08:19<00:00, 12.15it/s]
[INFO] ===== extracted face landmarks =====
[INFO] ===== extract semantics from data/processed/videos/May/ori_imgs to data/processed/videos/May/parsing =====
[INFO] ===== perform face tracking =====
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
100% 44.7M/44.7M [00:00<00:00, 107MB/s]
Traceback (most recent call last):
  File "/content/GeneFace/data_util/face_tracking/face_tracker.py", line 47, in <module>
    model_3dmm = Face_3DMM(os.path.join(dir_path, '3DMM'),
  File "/content/GeneFace/data_util/face_tracking/facemodel.py", line 15, in __init__
    DMM_info = np.load(os.path.join(
  File "/usr/local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/content/GeneFace/data_util/face_tracking/3DMM/3DMM_info.npy'
[INFO] ===== finished face tracking =====
[INFO] ===== extract background image from data/processed/videos/May/ori_imgs =====
  0% 0/304 [00:00<?, ?it/s][ WARN:0@2.416] global loadsave.cpp:248 findDecoder imread_('data/processed/videos/May/parsing/372.png'): can't open/read file: check file path/integrity
  0% 0/304 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/GeneFace/data_util/process.py", line 429, in <module>
    extract_background(processed_dir, ori_imgs_dir)
  File "/content/GeneFace/data_util/process.py", line 86, in extract_background
    bg = (parse_img[..., 0] == 255) & (parse_img[..., 1] == 255) & (parse_img[..., 2] == 255)
TypeError: 'NoneType' object is not subscriptable
[ WARN:0@0.031] global loadsave.cpp:248 findDecoder imread_('data/processed/videos/May/bc.jpg'): can't open/read file: check file path/integrity
[INFO] ===== extract head images for data/processed/videos/May =====
  0% 0/6073 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/GeneFace/data_util/process.py", line 433, in <module>
    extract_head(processed_dir)
  File "/content/GeneFace/data_util/process.py", line 138, in extract_head
    head_part = (parsing_img[:, :, 0] == 255) & (
TypeError: 'NoneType' object is not subscriptable
processed parsing 100
processed parsing 200
processed parsing 300
processed parsing 400
processed parsing 500
processed parsing 600
processed parsing 700
processed parsing 800
processed parsing 900
processed parsing 1000
processed parsing 1100
processed parsing 1200
processed parsing 1300
processed parsing 1400
processed parsing 1500
processed parsing 1600
processed parsing 1700
processed parsing 1800
processed parsing 1900
processed parsing 2000
processed parsing 2100
processed parsing 2200
processed parsing 2300
processed parsing 2400
processed parsing 2500
processed parsing 2600
processed parsing 2700
processed parsing 2800
processed parsing 2900
processed parsing 3000
processed parsing 3100
processed parsing 3200
processed parsing 3300
processed parsing 3400
processed parsing 3500
processed parsing 3600
processed parsing 3700
processed parsing 3800
processed parsing 3900
processed parsing 4000
processed parsing 4100
processed parsing 4200
processed parsing 4300
processed parsing 4400
processed parsing 4500
processed parsing 4600
processed parsing 4700
processed parsing 4800
processed parsing 4900
processed parsing 5000
processed parsing 5100
processed parsing 5200
processed parsing 5300
processed parsing 5400
processed parsing 5500
processed parsing 5600
processed parsing 5700
processed parsing 5800
processed parsing 5900
processed parsing 6000
[INFO] ===== extracted semantics =====
[INFO] ===== save transforms =====
Traceback (most recent call last):
  File "/content/GeneFace/data_util/process.py", line 446, in <module>
    save_transforms(processed_dir, ori_imgs_dir)
  File "/content/GeneFace/data_util/process.py", line 294, in save_transforms
    params_dict = torch.load(os.path.join(base_dir, 'track_params.pt'))
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/track_params.pt'
Loading the Wav2Vec2 Processor...
Downloading (…)rocessor_config.json: 100% 212/212 [00:00<00:00, 1.39MB/s]
Downloading (…)okenizer_config.json: 100% 138/138 [00:00<00:00, 1.06MB/s]
Downloading (…)lve/main/config.json: 100% 1.38k/1.38k [00:00<00:00, 11.5MB/s]
Downloading (…)olve/main/vocab.json: 100% 291/291 [00:00<00:00, 1.25MB/s]
Downloading (…)cial_tokens_map.json: 100% 85.0/85.0 [00:00<00:00, 618kB/s]
Loading the HuBERT Model...
Downloading pytorch_model.bin: 100% 1.26G/1.26G [00:09<00:00, 134MB/s]
Some weights of the model checkpoint at facebook/hubert-large-ls960-ft were not used when initializing HubertModel: ['lm_head.weight', 'lm_head.bias']
- This IS expected if you are initializing HubertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing HubertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2023-07-18 03:35:26.330142: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-18 03:35:28.229079: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Hubert extracted at data/processed/videos/May/aud_hubert.npy
Mel and F0 extracted at data/processed/videos/May/aud_mel_f0.npy
Traceback (most recent call last):
  File "/content/GeneFace/data_gen/nerf/extract_3dmm.py", line 16, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, network_size=4, device='cuda')
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D
| Unknow hparams:  []
| Hparams chains:  ['egs/egs_bases/radnerf/base.yaml', 'egs/egs_bases/radnerf/lm3d_radnerf.yaml', 'egs/datasets/videos/May/lm3d_radnerf.yaml']
| Hparams: 
;33;maccumulate_grad_batches: 1, ;33;mambient_out_dim: 2, ;33;mamp: True, ;33;mbase_config: ['egs/egs_bases/radnerf/lm3d_radnerf.yaml'], ;33;mbinary_data_dir: data/binary/videos, 
;33;mbound: 1, ;33;mcamera_offset: [0, 0, 0], ;33;mcamera_scale: 4.0, ;33;mclip_grad_norm: 0, ;33;mclip_grad_value: 0, 
;33;mcond_out_dim: 64, ;33;mcond_type: idexp_lm3d_normalized, ;33;mcond_win_size: 1, ;33;mcuda_ray: True, ;33;mdebug: False, 
;33;mdensity_thresh: 10, ;33;mdensity_thresh_torso: 0.01, ;33;mdesired_resolution: 2048, ;33;mdt_gamma: 0.00390625, ;33;meval_max_batches: 100, 
;33;mexp_name: , ;33;mfar: 0.9, ;33;mfinetune_lips: True, ;33;mfinetune_lips_start_iter: 200000, ;33;mgeo_feat_dim: 128, 
;33;mgrid_interpolation_type: linear, ;33;mgrid_size: 128, ;33;mgrid_type: tiledgrid, ;33;mgui_fovy: 21.24, ;33;mgui_h: 512, 
;33;mgui_max_spp: 1, ;33;mgui_radius: 3.35, ;33;mgui_w: 512, ;33;mhidden_dim_ambient: 128, ;33;mhidden_dim_color: 128, 
;33;mhidden_dim_sigma: 128, ;33;mindividual_embedding_dim: 4, ;33;mindividual_embedding_num: 13000, ;33;minfer: False, ;33;minfer_audio_source_name: , 
;33;minfer_bg_img_fname: , ;33;minfer_c2w_name: , ;33;minfer_cond_name: , ;33;minfer_lm3d_clamp_std: 2.5, ;33;minfer_lm3d_lle_percent: 0.0, 
;33;minfer_lm3d_smooth_sigma: 0.0, ;33;minfer_out_video_name: , ;33;minfer_scale_factor: 1.0, ;33;minfer_smo_std: 0.0, ;33;minfer_smooth_camera_path: True, 
;33;minfer_smooth_camera_path_kernel_size: 7, ;33;mlambda_ambient: 0.1, ;33;mlambda_lpips_loss: 0.01, ;33;mlambda_weights_entropy: 0.0001, ;33;mload_ckpt: , 
;33;mload_imgs_to_memory: False, ;33;mlog2_hashmap_size: 16, ;33;mlr: 0.0005, ;33;mmax_ray_batch: 4096, ;33;mmax_steps: 16, 
;33;mmax_updates: 250000, ;33;mmin_near: 0.05, ;33;mn_rays: 65536, ;33;mnear: 0.3, ;33;mnum_ckpt_keep: 1, 
;33;mnum_layers_ambient: 3, ;33;mnum_layers_color: 2, ;33;mnum_layers_sigma: 3, ;33;mnum_sanity_val_steps: 2, ;33;mnum_steps: 16, 
;33;mnum_valid_plots: 5, ;33;moptimizer_adam_beta1: 0.9, ;33;moptimizer_adam_beta2: 0.999, ;33;mprint_nan_grads: False, ;33;mprocessed_data_dir: data/processed/videos, 
;33;mraw_data_dir: data/raw/videos, ;33;mresume_from_checkpoint: 0, ;33;msave_best: True, ;33;msave_codes: ['tasks', 'modules', 'egs'], ;33;msave_gt: True, 
;33;mscheduler: exponential, ;33;mseed: 9999, ;33;msmo_win_size: 5, ;33;msmooth_lips: False, ;33;mtask_cls: tasks.radnerfs.radnerf.RADNeRFTask, 
;33;mtb_log_interval: 100, ;33;mtorso_head_aware: False, ;33;mtorso_individual_embedding_dim: 8, ;33;mtorso_shrink: 0.8, ;33;mupdate_extra_interval: 16, 
;33;mupsample_steps: 0, ;33;muse_window_cond: True, ;33;mval_check_interval: 2000, ;33;mvalid_infer_interval: 10000, ;33;mvalid_monitor_key: val_loss, 
;33;mvalid_monitor_mode: min, ;33;mvalidate: False, ;33;mvideo_id: May, ;33;mwarmup_updates: 0, ;33;mweight_decay: 0, 
;33;mwith_att: True, ;33;mwork_dir: , 
loading deepspeech ...
Traceback (most recent call last):
  File "/content/GeneFace/data_gen/nerf/binarizer.py", line 277, in <module>
    binarizer.parse(hparams['video_id'])
  File "/content/GeneFace/data_gen/nerf/binarizer.py", line 267, in parse
    ret = load_processed_data(processed_dir)
  File "/content/GeneFace/data_gen/nerf/binarizer.py", line 86, in load_processed_data
    deepspeech_features = np.load(deepspeech_npy_name)
  File "/usr/local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/May/aud_deepspeech.npy'

**Comment by SuperGoodGame** [comment]
I have the same problem ,do you deal with it ,can you tell me how to deal with it 
Thank you

**Comment by secnavo** [comment]
I also encounter the same problem. The problem should be the command "python data_util/process.py --video_id=$VIDEO_ID --task=2" in "data_gen/nerf/process_data.sh"; the error result is as follows:
[INFO] ===== extract audio labels for data/processed/videos/May/aud.wav =====
[INFO] ===== start extract esperanto =====
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[WARN] audio has 2 channels, only use the first.
[INFO] loaded audio stream data/processed/videos/May/aud.wav: (3886763,)
[INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto...
/data/anaconda3/envs/geneface/lib/python3.9/site-packages/transformers/configuration_utils.py:380: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
