### ISSUE TITLE
处理自己的视频数据出现问题

### ISSUE THREAD

**Issue by ZYBOBO** [yerfor/GeneFace#172]
params saved
[INFO] ===== finished face tracking =====
[INFO] ===== extract background image from data/processed/videos/jys1/ori_imgs =====
100%|███████████████████████████████████████████████████████████████████████| 339/339 [03:18<00:00,  1.70it/s]
[INFO] ===== extracted background image =====
[INFO] ===== extract head images for data/processed/videos/jys1 =====
100%|█████████████████████████████████████████████████████████████████████| 6767/6767 [01:41<00:00, 66.71it/s]
[INFO] ===== extracted head images =====
[INFO] ===== extract torso and gt images for data/processed/videos/jys1 =====
100%|█████████████████████████████████████████████████████████████████████| 6767/6767 [04:38<00:00, 24.26it/s]
[INFO] ===== extracted torso and gt images =====
[INFO] ===== save transforms =====
[INFO] ===== finished saving transforms =====
Loading the Wav2Vec2 Processor...
Loading the HuBERT Model...
2023-07-29 10:57:59.376227: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-29 10:57:59.421377: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-29 10:58:00.117671: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Hubert extracted at data/processed/videos/jys1/aud_hubert.npy
Mel and F0 extracted at data/processed/videos/jys1/aud_mel_f0.npy
loading the model from deep_3drecon/checkpoints/facerecon/epoch_20.pth
loading video ...
extracting 2D facial landmarks ...: 100%|█████████████████████████████████| 5143/5143 [02:33<00:00, 33.60it/s]
start extracting 3DMM...:   0%|                                                       | 0/160 [00:00<?, ?it/s]create rasterizer on device cuda:0
start extracting 3DMM...: 100%|█████████████████████████████████████████████| 160/160 [00:39<00:00,  4.06it/s]
3DMM coeff extracted at data/processed/videos/jys1/vid_coeff.npy
| Unknow hparams:  []
| Hparams chains:  ['egs/egs_bases/radnerf/base.yaml', 'egs/egs_bases/radnerf/lm3d_radnerf.yaml', 'egs/datasets/videos/jys1/lm3d_radnerf.yaml']
| Hparams: 
accumulate_grad_batches: 1, ambient_out_dim: 2, amp: True, base_config: ['egs/egs_bases/radnerf/lm3d_radnerf.yaml'], binary_data_dir: data/binary/videos, 
bound: 1, camera_offset: [0, 0, 0], camera_scale: 4.0, clip_grad_norm: 0, clip_grad_value: 0, 
cond_out_dim: 64, cond_type: idexp_lm3d_normalized, cond_win_size: 1, cuda_ray: True, debug: False, 
density_thresh: 10, density_thresh_torso: 0.01, desired_resolution: 2048, dt_gamma: 0.00390625, eval_max_batches: 100, 
exp_name: , far: 0.9, finetune_lips: True, finetune_lips_start_iter: 200000, geo_feat_dim: 128, 
grid_interpolation_type: linear, grid_size: 128, grid_type: tiledgrid, gui_fovy: 21.24, gui_h: 512, 
gui_max_spp: 1, gui_radius: 3.35, gui_w: 512, hidden_dim_ambient: 128, hidden_dim_color: 128, 
hidden_dim_sigma: 128, individual_embedding_dim: 4, individual_embedding_num: 13000, infer: False, infer_audio_source_name: , 
infer_bg_img_fname: , infer_c2w_name: , infer_cond_name: , infer_lm3d_clamp_std: 2.5, infer_lm3d_lle_percent: 0.0, 
infer_lm3d_smooth_sigma: 0.0, infer_out_video_name: , infer_scale_factor: 1.0, infer_smo_std: 0.0, infer_smooth_camera_path: True, 
infer_smooth_camera_path_kernel_size: 7, lambda_ambient: 0.1, lambda_lpips_loss: 0.01, lambda_weights_entropy: 0.0001, load_ckpt: , 
load_imgs_to_memory: False, log2_hashmap_size: 16, lr: 0.0005, max_ray_batch: 4096, max_steps: 16, 
max_updates: 250000, min_near: 0.05, n_rays: 65536, near: 0.3, num_ckpt_keep: 1, 
num_layers_ambient: 3, num_layers_color: 2, num_layers_sigma: 3, num_sanity_val_steps: 2, num_steps: 16, 
num_valid_plots: 5, optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.999, print_nan_grads: False, processed_data_dir: data/processed/videos, 
raw_data_dir: data/raw/videos, resume_from_checkpoint: 0, save_best: True, save_codes: ['tasks', 'modules', 'egs'], save_gt: True, 
scheduler: exponential, seed: 9999, smo_win_size: 5, smooth_lips: False, task_cls: tasks.radnerfs.radnerf.RADNeRFTask, 
tb_log_interval: 100, torso_head_aware: False, torso_individual_embedding_dim: 8, torso_shrink: 0.8, update_extra_interval: 16, 
upsample_steps: 0, use_window_cond: True, val_check_interval: 2000, valid_infer_interval: 10000, valid_monitor_key: val_loss, 
valid_monitor_mode: min, validate: False, video_id: jys1, warmup_updates: 0, weight_decay: 0, 
with_att: True, work_dir: , 
loading deepspeech ...
loading Esperanto ...
loading hubert ...
loading Mel and F0 ...
loading 3dmm coeff ...
calculating lm3d ...
loading train_val.json ...
data_gen/nerf/binarizer.py:136: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  bg_img = imageio.imread(background_img_name)
Binarizing train set:  84%|████████████████████████████████████▊       | 5143/6151 [00:00<00:00, 22210.18it/s]
Traceback (most recent call last):
  File "data_gen/nerf/binarizer.py", line 277, in <module>
    binarizer.parse(hparams['video_id'])
  File "data_gen/nerf/binarizer.py", line 267, in parse
    ret = load_processed_data(processed_dir)
  File "data_gen/nerf/binarizer.py", line 186, in load_processed_data
    'exp': exp_arr[idx],
IndexError: index 5143 is out of bounds for axis 0 with size 5143
请问以上index越界问题该怎么解决？

**Comment by BingliangLi** [comment]
请问解决了吗

**Comment by ZYBOBO** [comment]
解决了&nbsp;


且行且珍惜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bingliang ***@***.***&gt;; 
发送时间: 2023年8月7日(星期一) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yerfor/GeneFace] 处理自己的视频数据出现问题 (Issue #172)





 
请问解决了吗

**Comment by BingliangLi** [comment]
请问是怎么解决的呀

**Comment by ZYBOBO** [comment]
就自己处理的视频帧率为50，而提供的视频帧率为25，需要对帧率进行调整&nbsp;


且行且珍惜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bingliang ***@***.***&gt;; 
发送时间: 2023年8月7日(星期一) 下午2:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yerfor/GeneFace] 处理自己的视频数据出现问题 (Issue #172)





 
请问是怎么解决的呀
