### ISSUE TITLE
data/processed/videos/May/ori_imgs/0.lms not found.

### ISSUE THREAD

**Issue by Alpacolypse** [yerfor/GeneFace#173]
I see several posts about this issue, but there doesn't seem to an answer. 

I'm trying to run inference on the May video and Zozo audio.

I have gone through the prepare_env steps, verified installation, downloaded and extracted the lrs3.zip and May.zip checkpoints/binaries and placed them in the respective folders. 

Getting the following error when running 

`bash scripts/infer_lm3d_radnerf.sh`

`Traceback (most recent call last):
  File "/home/alpacolypse/workplace/ai_interview/geneface_test/GeneFace/inference/nerfs/radnerf_gui.py", line 590, in <module>
    inferencer = LM3d_RADNeRFInfer(hparams)
  File "/home/alpacolypse/workplace/ai_interview/geneface_test/GeneFace/inference/nerfs/lm3d_radnerf_infer.py", line 15, in __init__
    self.dataset = self.dataset_cls('trainval', training=False)
  File "/home/alpacolypse/workplace/ai_interview/geneface_test/GeneFace/tasks/radnerfs/dataset_utils.py", line 104, in __init__
    lms = np.loadtxt(os.path.join(hparams['processed_data_dir'],hparams['video_id'], 'ori_imgs', str(img_id) + '.lms')) # [68, 2]
  File "/home/alpacolypse/anaconda3/envs/geneface3/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1356, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/alpacolypse/anaconda3/envs/geneface3/lib/python3.9/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/alpacolypse/anaconda3/envs/geneface3/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/alpacolypse/anaconda3/envs/geneface3/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: data/processed/videos/May/ori_imgs/0.lms not found.`

The data/processed/videos/May/ori_imgs/0.lms does not exist. This seems to be generated by `data_gen/nerf/process_data.sh` but the quickstart/docs don't mention the usage of this if we are doing inference on the pre-trained May model.

**Comment by Alpacolypse** [comment]
Turns out I was following the old quickstart for v1.1.0. We need to run process_data.sh for the May video as well for it to generated the lms data.
