### ISSUE TITLE
使用自己视频时，出现错误

### ISSUE THREAD

**Issue by zydp** [yerfor/GeneFace#174]
您好，请教一下。
我在使用自己准备的视频，进行数据预处理的时候，出现错误
---
操作步骤：
conda activate geneface
export PYTHONPATH=./
export VIDEO_ID=3244
CUDA_VISIBLE_DEVICES=0 data_gen/nerf/process_data.sh $VIDEO_ID
---
出现错误：
Traceback (most recent call last):
  File "/data/daiping/virtualHuman/GeneFace-main/data_util/process.py", line 447, in <module>
    save_transforms(processed_dir, ori_imgs_dir)
  File "/data/daiping/virtualHuman/GeneFace-main/data_util/process.py", line 295, in save_transforms
    params_dict = torch.load(os.path.join(base_dir, 'track_params.pt'))
  File "/root/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] **No such file or directory: 'data/processed/videos/3244/track_params.pt'**
---

**Comment by zydp** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/3244/track_params.pt'
：请问我该如何才能生成这个track_params.pt的文件
当前情况下，我只准备了一个3244.mp4的视频，还需要准备其他的文件吗?

**Comment by zydp** [comment]
找到问题：
因为我自备的视频分辨率过高导致前面有一些步骤出错

**Comment by Pythonpa** [comment]
So,it must need 512x512?
