### ISSUE TITLE
bash scripts/infer_postnet.sh  

### ISSUE THREAD

**Issue by cano2135** [yerfor/GeneFace#179]
| Unknow hparams:  []
Traceback (most recent call last):
  File "/home/ai_linux1/Desktop/GITHUB/GeneFace-main/inference/postnet/postnet_infer.py", line 133, in <module>
    set_hparams()
  File "/home/ai_linux1/Desktop/GITHUB/GeneFace-main/utils/commons/hparams.py", line 46, in set_hparams
    assert os.path.exists(args.config)
AssertionError

Do you have any ideas how to solve this problem?thanks

![Screenshot from 2023-08-11 11-35-11](https://github.com/yerfor/GeneFace/assets/73460753/7f4f7873-fd19-4b8f-9d30-326a14f5b4bf)

**Comment by feifeitu1** [comment]
Hello，Do you address this problem,I meet the same question?

**Comment by feifeitu1** [comment]
Maybe because I name the folder errorly.
![Snipaste_2023-10-10_11-01-17](https://github.com/yerfor/GeneFace/assets/55725526/bd3cc802-0205-4648-a203-33b60f894d5c)
