### ISSUE TITLE
 CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by angelandy** [yerfor/GeneFace#184]
start extracting 3DMM...:   0%|                                                                                                                                         | 0/189 [00:00<?, ?it/s]create rasterizer on device cuda:0
start extracting 3DMM...:   0%|                                                                                                                                         | 0/189 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "data_gen/nerf/extract_3dmm.py", line 112, in <module>
    process_video(video_fname, out_fname, skip_tmp=False)
  File "data_gen/nerf/extract_3dmm.py", line 75, in process_video
    coeff, align_img = face_reconstructor.recon_coeff(batched_images, batched_lm5, return_image = True)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/GeneFace/deep_3drecon/reconstructor.py", line 79, in recon_coeff
    self.model.forward()
  File "/data/GeneFace/deep_3drecon/deep_3drecon_models/facerecon_model.py", line 139, in forward
    self.pred_mask, _, self.pred_face = self.renderer(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/GeneFace/deep_3drecon/util/mesh_renderer.py", line 105, in forward
    fragments = self.rasterizer(mesh, cameras = cameras, raster_settings = raster_settings)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 252, in forward
    pix_to_face, zbuf, bary_coords, dists = rasterize_meshes(
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 223, in rasterize_meshes
    pix_to_face, zbuf, barycentric_coords, dists = _RasterizeFaceVerts.apply(
  File "/opt/conda/lib/python3.8/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 297, in forward
    pix_to_face, zbuf, barycentric_coords, dists = _C.rasterize_meshes(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

这个是什么错误？是我显卡不够显存吗。驱动什么的都没有问题

**Comment by fjesikfjdskl** [comment]
你好请问解决了吗
