### ISSUE TITLE
Top Common Error? Processing Target Person Video

### ISSUE THREAD

**Issue by RARE-UK** [yerfor/GeneFace#188]
How can this be troubleshooted? We have spent more than a week trying to resolve issues with this program. Please let us know.

The MAY example video works correctly, using custom video content mp4 the model cannot complete training...

120 of 121 done
params saved
[INFO] ===== finished face tracking =====
[INFO] ===== extract background image from data/processed/videos/MTK/ori_imgs =====
100%|████████████████████████████████████████████████████████████████████████████| 301/301 [01:31<00:00,  3.30it/s][INFO] ===== extracted background image =====
[INFO] ===== extract head images for data/processed/videos/MTK =====
100%|██████████████████████████████████████████████████████████████████████████| 6003/6003 [01:05<00:00, 92.07it/s][INFO] ===== extracted head images =====
[INFO] ===== extract torso and gt images for data/processed/videos/MTK =====
100%|██████████████████████████████████████████████████████████████████████████| 6003/6003 [02:29<00:00, 40.20it/s][INFO] ===== extracted torso and gt images =====
[INFO] ===== save transforms =====
[INFO] ===== finished saving transforms =====
Loading the Wav2Vec2 Processor...
Loading the HuBERT Model...
2023-08-26 00:17:47.047964: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-26 00:17:47.075708: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-26 00:17:47.508668: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Hubert extracted at data/processed/videos/MTK/aud_hubert.npy
Mel and F0 extracted at data/processed/videos/MTK/aud_mel_f0.npy
loading the model from deep_3drecon/checkpoints/facerecon/epoch_20.pth
loading video ...
extracting 2D facial landmarks ...: 100%|██████████████████████████████████████| 5056/5056 [04:32<00:00, 18.54it/s]start extracting 3DMM...:   0%|                                                            | 0/158 [00:00<?, ?it/s]create rasterizer on device cuda:0
start extracting 3DMM...: 100%|██████████████████████████████████████████████████| 158/158 [00:40<00:00,  3.88it/s]3DMM coeff extracted at data/processed/videos/MTK/vid_coeff.npy
| Unknow hparams:  []
Traceback (most recent call last):
  File "/home/m/GeneFace/data_gen/nerf/binarizer.py", line 14, in <module>
    set_hparams()
  File "/home/m/GeneFace/utils/commons/hparams.py", line 46, in set_hparams
    assert os.path.exists(args.config)
AssertionError

**Comment by weiwenping-cn** [comment]
process_data.sh > python data_gen/nerf/binarizer.py --config=egs/datasets/videos/$1/lm3d_radnerf.yaml

> Refer to the MAY example video to configure your own configuration file in this directory. Normally, you only need to change the video name

![image](https://github.com/yerfor/GeneFace/assets/48076164/9de2944b-4954-453c-adc8-2743b28a11a7)

**Comment by tailangjun** [comment]
这个错误应该是第 10步 python data_gen/nerf/binarizer.py --config=egs/datasets/videos/$VIDEO_ID/lm3d_radnerf.yaml 产生的，应该是你传入的 config路径参数错误，楼主可以检查一下
