### ISSUE TITLE
 How to solve this error ''raise ValueError('Unknown mat file type, version %s, %s' % ret) ValueError: Unknown mat file type, version 97, 116''

### ISSUE THREAD

**Issue by Anthony0u** [yerfor/GeneFace#224]
(geneface) root@autodl-container-b94c46a1f4-577005f2:~/GeneFace-1.1.0/data_util/face_tracking# python convert_BFM.py
Traceback (most recent call last):
  File "/root/GeneFace-1.1.0/data_util/face_tracking/convert_BFM.py", line 5, in <module>
    original_BFM = loadmat('/root/GeneFace-1.1.0/data_util/face_tracking/convert_BFM.py')
  File "/root/miniconda3/envs/geneface/lib/python3.9/site-packages/scipy/io/matlab/mio.py", line 225, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/root/miniconda3/envs/geneface/lib/python3.9/site-packages/scipy/io/matlab/mio.py", line 74, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/root/miniconda3/envs/geneface/lib/python3.9/site-packages/scipy/io/matlab/miobase.py", line 231, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 97, 116

**Comment by Anthony0u** [comment]
I have asked ChatGPT ,and tried the suggestions it offered,but it still doesn't works.

**Comment by husthzy** [comment]
Please read the docs/prepare_env/install_guide.md, download the BFM2009 model

You can obtain a file named `BaselFaceModel.tgz`, extract a file named `01_MorphableModel.mat` from it and save it into the directory `./deep_3drecon/BFM/`
