### ISSUE TITLE
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Anthony0u** [yerfor/GeneFace#229]
(process_lrs3) root@autodl-container-c49d4d860b-9ff62b42:~/GeneFace-1.1.0# CCUDA_VISSIBLE_DEVICES=0 python deep_3drecon/test.py
Traceback (most recent call last):
  File "deep_3drecon/test.py", line 67, in <module>
    opt = TestOptions().parse()  # get test options
  File "/root/GeneFace-1.1.0/deep_3drecon/options/base_options.py", line 124, in parse
    opt = self.gather_options()
  File "/root/GeneFace-1.1.0/deep_3drecon/options/base_options.py", line 73, in gather_options
    model_option_setter = deep_3drecon_models.get_option_setter(model_name)
  File "/root/GeneFace-1.1.0/deep_3drecon/deep_3drecon_models/__init__.py", line 50, in get_option_setter
    model_class = find_model_using_name(model_name)
  File "/root/GeneFace-1.1.0/deep_3drecon/deep_3drecon_models/__init__.py", line 33, in find_model_using_name
    modellib = importlib.import_module(model_filename)
  File "/root/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/GeneFace-1.1.0/deep_3drecon/deep_3drecon_models/facerecon_model.py", line 8, in <module>
    from .bfm import ParametricFaceModel
  File "/root/GeneFace-1.1.0/deep_3drecon/deep_3drecon_models/bfm.py", line 8, in <module>
    from deep_3drecon.util.load_mats import transferBFM09
  File "/root/GeneFace-1.1.0/deep_3drecon/__init__.py", line 1, in <module>
    from .reconstructor import *
  File "/root/GeneFace-1.1.0/deep_3drecon/reconstructor.py", line 9, in <module>
    from .deep_3drecon_models.facerecon_model import FaceReconModel
  File "/root/GeneFace-1.1.0/deep_3drecon/deep_3drecon_models/facerecon_model.py", line 11, in <module>
    from deep_3drecon.util.mesh_renderer import MeshRenderer
  File "/root/GeneFace-1.1.0/deep_3drecon/util/mesh_renderer.py", line 4, in <module>
    import pytorch3d.ops
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch3d/ops/__init__.py", line 5, in <module>
    from .graph_conv import GraphConv
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch3d/ops/graph_conv.py", line 8, in <module>
    from pytorch3d import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by Anthony0u** [comment]
how can I handle this？ IS it because of wrong cuda version that not match pytorch3d?

**Comment by jackyin68** [comment]
only supports 512x512 and 25 fps videos
