### ISSUE TITLE
安装GENEFACE时候，出现错误了，大神们帮帮忙！

### ISSUE THREAD

**Issue by zhanga9** [yerfor/GeneFace#240]
(base) geneface@DESKTOP-MMTJN6M:~$ conda activate geneface
(geneface) geneface@DESKTOP-MMTJN6M:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
(geneface) geneface@DESKTOP-MMTJN6M:~$ python --version
Python 3.9.16
(geneface) geneface@DESKTOP-MMTJN6M:~$ export CUDA_HOME=/usr/local/cuda-11.3
(geneface) geneface@DESKTOP-MMTJN6M:~$ export PATH=$CUDA_HOME/bin:$PATH
rt LD_(geneface) geneface@DESKTOP-MMTJN6M:~$ export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
(geneface) geneface@DESKTOP-MMTJN6M:~$ cd ~/GeneFace-main
(geneface) geneface@DESKTOP-MMTJN6M:~/GeneFace-main$ bash docs/prepare_env/install_ext.sh
Processing ./modules/radnerfs/encoders/freqencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: freqencoder
  Building wheel for freqencoder (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.3'
      running bdist_wheel
      running build
      running build_ext
      building '_freqencoder' extension
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/build
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/build/temp.linux-x86_64-cpython-39
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/build/temp.linux-x86_64-cpython-39/home
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/build/temp.linux-x86_64-cpython-39/home/geneface
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs/encoders
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/src
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/geneface/GeneFace-main/modules/radnerfs/encoders/freqencoder/setup.py", line 33, in <module>
          setup(
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
          build_ext.build_extensions(self)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 557, in unix_wrap_ninja_compile
          cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 456, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1626, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for freqencoder
  Running setup.py clean for freqencoder
Failed to build freqencoder
ERROR: Could not build wheels for freqencoder, which is required to install pyproject.toml-based projects
Processing ./modules/radnerfs/encoders/shencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: shencoder
  Building wheel for shencoder (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.3'
      running bdist_wheel
      running build
      running build_ext
      building '_shencoder' extension
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/build
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/build/temp.linux-x86_64-cpython-39
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/build/temp.linux-x86_64-cpython-39/home
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/build/temp.linux-x86_64-cpython-39/home/geneface
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs/encoders
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/src
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/geneface/GeneFace-main/modules/radnerfs/encoders/shencoder/setup.py", line 32, in <module>
          setup(
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
          build_ext.build_extensions(self)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 557, in unix_wrap_ninja_compile
          cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 456, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1626, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for shencoder
  Running setup.py clean for shencoder
Failed to build shencoder
ERROR: Could not build wheels for shencoder, which is required to install pyproject.toml-based projects
Processing ./modules/radnerfs/encoders/gridencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: gridencoder
  Building wheel for gridencoder (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.3'
      running bdist_wheel
      running build
      running build_ext
      building '_gridencoder' extension
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/build
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/build/temp.linux-x86_64-cpython-39
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/build/temp.linux-x86_64-cpython-39/home
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/build/temp.linux-x86_64-cpython-39/home/geneface
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs/encoders
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder
      creating /home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/build/temp.linux-x86_64-cpython-39/home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/src
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/geneface/GeneFace-main/modules/radnerfs/encoders/gridencoder/setup.py", line 32, in <module>
          setup(
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
          build_ext.build_extensions(self)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 557, in unix_wrap_ninja_compile
          cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 456, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/home/geneface/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1626, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gridencoder
  Running setup.py clean for gridencoder
Failed to build gridencoder
ERROR: Could not build wheels for gridencoder, which is required to install pyproject.toml-based projects
Processing ./modules/radnerfs/raymarching
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: raymarching-face
  Building wheel for raymarching-face (setup.py) ... done
  Created wheel for raymarching-face: filename=raymarching_face-0.0.0-cp39-cp39-linux_x86_64.whl size=163575 sha256=677e47f346e3a7e4a5270198f400acdb55b4571612963c7a587b11c68cc99874
  Stored in directory: /tmp/pip-ephem-wheel-cache-03xn7p5o/wheels/d6/53/d7/0d5ae54af184fca31a7f0edc04949f0bc8359f0558b0c7f9a3
Successfully built raymarching-face
Installing collected packages: raymarching-face
  Attempting uninstall: raymarching-face
    Found existing installation: raymarching-face 0.0.0
    Uninstalling raymarching-face-0.0.0:
      Successfully uninstalled raymarching-face-0.0.0
Successfully installed raymarching-face-0.0.0
(geneface) geneface@DESKTOP-MMTJN6M:~/GeneFace-main$

**Comment by zhieie** [comment]
大佬，我也遇到了这个问题，请问你解决了吗
