### ISSUE TITLE
raymarching_face error dosn't solve even with pip intall raymarching

### ISSUE THREAD

**Issue by saba99** [yerfor/GeneFace#251]
ModuleNotFoundError: No module named '_raymarching_face'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/drive/MyDrive/GeneFace/inference/nerfs/lm3d_radnerf_infer.py", line 99, in <module>
    LM3d_RADNeRFInfer.example_run(inp)
  File "/content/drive/MyDrive/GeneFace/inference/nerfs/base_nerf_infer.py", line 299, in example_run
    infer_ins = cls(hp)
  File "/content/drive/MyDrive/GeneFace/inference/nerfs/lm3d_radnerf_infer.py", line 13, in __init__
    super().__init__(hparams, device)
  File "/content/drive/MyDrive/GeneFace/inference/nerfs/base_nerf_infer.py", line 62, in __init__
    self.task_cls = getattr(importlib.import_module(pkg), cls_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/GeneFace/tasks/radnerfs/radnerf_torso.py", line 9, in <module>
    from modules.radnerfs.radnerf import RADNeRF
  File "/content/drive/MyDrive/GeneFace/modules/radnerfs/radnerf.py", line 6, in <module>
    from modules.radnerfs.renderer import NeRFRenderer
  File "/content/drive/MyDrive/GeneFace/modules/radnerfs/renderer.py", line 10, in <module>
    import modules.radnerfs.raymarching as raymarching
  File "/content/drive/MyDrive/GeneFace/modules/radnerfs/raymarching/__init__.py", line 1, in <module>
    from .raymarching import *
  File "/content/drive/MyDrive/GeneFace/modules/radnerfs/raymarching/raymarching.py", line 12, in <module>
    from .backend import _backend
  File "/content/drive/MyDrive/GeneFace/modules/radnerfs/raymarching/backend.py", line 31, in <module>
    _backend = load(name='_raymarching_face',
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1736, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 2136, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /root/.cache/torch_extensions/py310_cu121/_raymarching_face/_raymarching_face.so: cannot open shared object file: No such file or directory

**Comment by ChengsongLu** [comment]
same

**Comment by yerfor** [comment]
Hi, torch-ngp only support CUDA 10.x and CUDA 11.x.

Besides, we have released the code of GeneFace++ (https://github.com/yerfor/GeneFacePlusPlus). We recommend you turn to this upgraded version for better performance.
