### ISSUE TITLE
Unknow hparams:  [] when running on a custom video

### ISSUE THREAD

**Issue by natalya118** [yerfor/GeneFace#254]
Hi! I'm getting an error when trying to binarize a custom video. Everything is working ok with May (after changing _2D to TWO_D). Did anyone have the same one?

Error:
...
Hubert extracted at data/processed/videos/BabsResized/aud_hubert.npy
Mel and F0 extracted at data/processed/videos/BabsResized/aud_mel_f0.npy
loading the model from deep_3drecon/checkpoints/facerecon/epoch_20.pth
loading video ...
extracting 2D facial landmarks ...: 100%|█████| 597/597 [00:49<00:00, 12.03it/s]
start extracting 3DMM...:   0%|                          | 0/18 [00:00<?, ?it/s]create rasterizer on device cuda:0
start extracting 3DMM...: 100%|█████████████████| 18/18 [00:05<00:00,  3.16it/s]
3DMM coeff extracted at data/processed/videos/BabsResized/vid_coeff.npy
| Unknow hparams:  []
Traceback (most recent call last):
  File "/home/d/GeneFace/data_gen/nerf/binarizer.py", line 14, in <module>
    set_hparams()
  File "/home/d/GeneFace/utils/commons/hparams.py", line 46, in set_hparams
    assert os.path.exists(args.config)
AssertionError

**Comment by kikiloveswift** [comment]
Maybe you didn't read the code, locate in `data_gen/nerf/process_data.sh` at line 28, `--config=egs/datasets/videos/$1/lm3d_radnerf.yaml`
you need copy one lm3d_radnerf in your directory, So you can close this issue.

**Comment by kikiloveswift** [comment]
Change your video name to May.mp4 or read the code structure at `egs/datasets/videos`

**Comment by kikiloveswift** [comment]
Make sure your video is 25 FPS and refs=1.
