### ISSUE TITLE
The detected CUDA version (12.3) mismatches the version that was used to compile PyTorch (11.3). Please make sure to use the same CUDA versions.

### ISSUE THREAD

**Issue by enrico310786** [yerfor/GeneFace#266]
Hi,

i try to install your project on my machine. I have an EC2 AWS instance with a Tesla T4 GPU with installed CUDA Version: 12.3.

I follow your installation guide and make the following steps 

1) conda create -n geneface python=3.9.16 -y
2) conda activate geneface
3) conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch (conda clean --all)
4) conda install -c fvcore -c iopath -c conda-forge fvcore iopath -y
5) conda install -c bottler nvidiacub -y
6) conda install pytorch3d -c pytorch3d -y ( pytorch3d-0.7.4            |py39_cu113_pyt1110        27.2 MB  pytorch3d)
7) sudo apt-get install libasound2-dev portaudio19-dev
8) pip install -r docs/prepare_env/requirements.txt (change verson of tensorflow to tensorflow-2.13.0)
9) conda install ffmpeg

So far so good. But when i run the command 

bash docs/prepare_env/install_ext.sh

i obtain the following errors

*****************************************

Building wheels for collected packages: raymarching-face
  Building wheel for raymarching-face (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/randellini/GeneFace/modules/radnerfs/raymarching/setup.py", line 45, in <module>
          setup(
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 410, in build_extensions
          self._check_cuda_version()
        File "/home/shared/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 787, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.3) mismatches the version that was used to compile
      PyTorch (11.3). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for raymarching-face
  Running setup.py clean for raymarching-face
Failed to build raymarching-face
ERROR: Could not build wheels for raymarching-face, which is required to install pyproject.toml-based projects

*****************************************

I thought that by installing in the conda environment the cudatoolkit=11.3 by the command

 install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 

it would still work. It seems like no. Could you give me some suggestions on how to proceed to install the project with my CUDA version 12.3?

Thanks in advance

**Comment by yerfor** [comment]
Hi, please make sure that the cuda located at `/usr/local/cuda` also at version 11.3. Becasuse the torch-ngp extension requires native CUDA (not the python binding) to compile the extension.

Besides, we have released the code of GeneFace++ (https://github.com/yerfor/GeneFacePlusPlus). We recommend you turn to this upgraded version for better performance.
