### ISSUE TITLE
请问从视频中提取HuBERT特征时，会爆内存无法正常运行，有办法解决吗？

### ISSUE THREAD

**Issue by TschillionWong** [yerfor/GeneFace#45]
在运行`CUDA_VISIBLE_DEVICES=0 python data_gen/nerf/extract_hubert.py --video_id=$VIDEO_ID`这一步代码时，即使机器有23G的空闲内存也会无法正常运行，请问运行时占用大量内存的情况是正常的吗？
如果是的话，想问一下您在这一步大概需要多少内存？
如果不是的话，有什么解决办法吗，或者时可以让它跑在显存上吗？

**Comment by yerfor** [comment]
你好，在早版本的代码中我们使用cpu运行hubert，并且忘记no_grad，导致内存里会累计每个chunk的梯度。在最新的代码中我们已经转向使用cuda，并且使用了no_grad。所以pull一下最新的代码，应该可以解决你的问题。

**Comment by zhangziliang04** [comment]
@yerfor 代码中的实现，发现有一个大时长的限制，实测过不能超过3分钟，【用4分钟的视频实测，异常】，不知道这个问题，是否同步解决了。如果采用cuda，原则上音频文件的长度，应该可以很长，不知道有没有实测过一个上限的值是多少？

**Comment by yerfor** [comment]
@zhangziliang04  你好，最新cuda实现我测试过4分钟的音频（`May.mp4`），成功提取了特征，并且提取速度相比cpu有了很大的提高，你可以测试一下。

**Comment by zhangziliang04** [comment]
感谢。我更新一下代码先。之前代码让我注释了太多，乱糟糟了。

**Comment by Gpwner** [comment]
处理以下video时：
```
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 13.6 MiB
Duration                                 : 5 min 0 s
Overall bit rate                         : 381 kb/s
Writing application                      : Lavf60.4.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 5 min 0 s
Source duration                          : 5 min 0 s
Bit rate                                 : 229 kb/s
Maximum bit rate                         : 251 kb/s
Width                                    : 512 pixels
Height                                   : 512 pixels
Display aspect ratio                     : 1.000
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.035
Stream size                              : 8.19 MiB (60%)
Source stream size                       : 8.82 MiB (65%)
Writing library                          : x264 core 164 r3106 eaa68fa
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Color range                              : Full
Matrix coefficients                      : BT.470 System B, BT.470 System G
mdhd_Duration                            : 300120

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 5 min 0 s
Source duration                          : 5 min 0 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 4.59 MiB (34%)
Source stream size                       : 4.59 MiB (34%)
Default                                  : Yes
Alternate group                          : 1
```

会出错：

```
Traceback (most recent call last):
  File "/home/foo/GeneFace/data_gen/nerf/extract_hubert_mel_f0.py", line 17, in <module>
    hubert_hidden = get_hubert_from_16k_speech(speech_16k)
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/foo/GeneFace/data_gen/process_lrs3/process_audio_hubert.py", line 56, in get_hubert_from_16k_speech
    hidden_states = hubert_model.forward(input_values).last_hidden_state  # [B=1, T=pts//320, hid=1024]
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/transformers/models/hubert/modeling_hubert.py", line 1064, in forward
    extract_features = self.feature_extractor(input_values)
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/transformers/models/hubert/modeling_hubert.py", line 358, in forward
    hidden_states = conv_layer(hidden_states)
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/transformers/models/hubert/modeling_hubert.py", line 228, in forward
    hidden_states = self.conv(hidden_states)
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 307, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 303, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size

Process finished with exit code 1

```



当我将
```
clip_length = stride * 1000
```
修改成：
```
clip_length = stride * 900
```
时才能正常运行，不知道这么修改和您的预期是否一致，会不会影响下游效果？

**Comment by yerfor** [comment]
问题不大，clip_length其实就等价于提取hubert时hubert model infer的batch_size

**Comment by Gpwner** [comment]
@yerfor 好的，感谢。
