### ISSUE TITLE
bc_img error

### ISSUE THREAD

**Issue by vianseto** [yerfor/GeneFace#59]
Hey, I ran the bash scripts/infer_lm3d_nerf.sh script and encountered a KeyError with the message 'bc_img'. I have no idea what went wrong with the code. Can you help me please?

This the full error message:
```shell
/home/user/anaconda3/envs/geneface/lib/python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (None)/charset_normalizer (3.1.0) doesn't match a supported version!
  warnings.warn(
| Unknow hparams:  []
| Hparams chains:  ['egs/egs_bases/nerf/base.yaml', 'egs/egs_bases/nerf/lm3d_nerf.yaml', 'egs/egs_bases/nerf/lm3d_nerf_torso.yaml', 'checkpoints/May/lm3d_nerf_torso/config.yaml']
| Hparams: 
accumulate_grad_batches: 1, amp: False, base_config: ['egs/egs_bases/nerf/lm3d_nerf_torso.yaml'], binary_data_dir: data/binary/videos, clip_grad_norm: 0, 
clip_grad_value: 0, cond_dim: 64, cond_type: idexp_lm3d_normalized, cond_win_size: 1, debug: False, 
embedding_args: {'multi_res_pos': 10, 'multi_res_views': 4}, eval_max_batches: 100, exp_name: , far: 0.9, gen_dir_name: , 
head_model_dir: checkpoints/May/lm3d_nerf, hidden_size: 256, in_rect_percent: 0.95, infer: True, infer_audio_source_name: data/raw/val_wavs/zozo.wav, 
infer_c2w_name: , infer_close_mouth_when_sil: False, infer_cond_name: infer_out/May/pred_lm3d/zozo.npy, infer_eye_blink_ref_frames_end_idx: , infer_eye_blink_ref_frames_start_idx: , 
infer_inject_eye_blink_mode: none, infer_lm3d_clamp_std: 3.0, infer_lm3d_lle_percent: 0.0, infer_lm3d_smooth_sigma: 0.0, infer_out_video_name: infer_out/May/pred_video/zozo_infer_torso_nerf.mp4, 
infer_pose_smooth_sigma: 2.0, infer_scale_factor: 1.0, infer_sil_ref_frame_idx: , infer_smo_std: 0.0, lm3d_scale_factor: 1.0, 
load_ckpt: , load_imgs_to_memory: False, lr: 0.0005, max_updates: 400000, n_rays: 1600, 
n_samples_per_ray: 32, n_samples_per_ray_fine: 128, near: 0.3, no_smo_iterations: 0, num_ckpt_keep: 1, 
num_sanity_val_steps: 0, num_valid_plots: 5, optimizer_adam_beta1: 0.9, optimizer_adam_beta2: 0.999, print_nan_grads: False, 
processed_data_dir: data/processed/videos, raw_data_dir: data/raw/videos, rays_sampler_type: uniform, resume_from_checkpoint: 0, save_best: True, 
save_codes: ['tasks', 'modules', 'egs'], save_gt: True, scheduler: exponential, seed: 9999, smo_win_size: 5, 
task_cls: tasks.nerfs.lm3d_nerf_torso.Lm3dNeRFTorsoTask, tb_log_interval: 100, use_color: True, use_window_cond: True, val_check_interval: 10000, 
valid_infer_interval: 10000, valid_monitor_key: val_loss, valid_monitor_mode: min, validate: False, video_id: May, 
warmup_updates: 0, weight_decay: 0, with_att: True, work_dir: checkpoints/May/lm3d_nerf_torso, 
Traceback (most recent call last):
  File "inference/nerfs/lm3d_nerf_infer.py", line 148, in <module>
    LM3dNeRFInfer.example_run(inp)
  File "/home/user/vian/GF/GeneFace/inference/nerfs/base_nerf_infer.py", line 299, in example_run
    infer_ins = cls(hp)
  File "/home/user/vian/GF/GeneFace/inference/nerfs/base_nerf_infer.py", line 57, in __init__
    self.dataset = self.dataset_cls('trainval')
  File "/home/user/vian/GF/GeneFace/tasks/nerfs/dataset_utils.py", line 33, in __init__
    self.bc_img = torch.from_numpy(ds_dict['bc_img']).float() / 255.
KeyError: 'bc_img'
```

**Comment by yerfor** [comment]
Hi, this is because we have updated the codebase, in which `bc_img` in the `trainval_dataset.npy` is renamed to `bg_img`. Please pull the newest version of the code. 

Besides, in the latest release, we provide support for RAD-NeRF, it is more efficient that the lm3d_nerf. You can try with `inference/infer_lm3d_radnerf.sh`
