### ISSUE TITLE
0.lms not found.

### ISSUE THREAD

**Issue by Gpwner** [yerfor/GeneFace#61]
当运行以下shell脚本时出错，请帮忙看看:
```
bash scripts/infer_lm3d_radnerf.sh
# bash scripts/infer_radnerf_gui.sh # you can also use GUI provided by RADNeRF
```

错误：
````
Traceback (most recent call last):
  File "/home/foo/GeneFace/inference/nerfs/lm3d_radnerf_infer.py", line 99, in <module>
    LM3d_RADNeRFInfer.example_run(inp)
  File "/home/foo/GeneFace/inference/nerfs/base_nerf_infer.py", line 299, in example_run
    infer_ins = cls(hp)
  File "/home/foo/GeneFace/inference/nerfs/lm3d_radnerf_infer.py", line 15, in __init__
    self.dataset = self.dataset_cls('trainval', training=False)
  File "/home/foo/GeneFace/tasks/radnerfs/dataset_utils.py", line 104, in __init__
    lms = np.loadtxt(os.path.join(hparams['processed_data_dir'],hparams['video_id'], 'ori_imgs', str(img_id) + '.lms')) # [68, 2]
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1338, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/npyio.py", line 975, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/foo/miniconda3/envs/geneface/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: data/processed/videos/May/ori_imgs/0.lms not found.

```

**Comment by Gpwner** [comment]
data目录下没有processed文件夹，请问这个生成逻辑在哪

**Comment by Gpwner** [comment]
我
