### ISSUE TITLE
KeyError: 'n_samples_per_ray'

### ISSUE THREAD

**Issue by ax0057** [yerfor/GeneFace#70]
您好，感谢您发布的优秀的工作。我在按照您的说明train_models.md 使用示例视频进行生成时，（步骤5. 使用GeneFace生成说话人视频），运行bash scripts/infer_lm3d_nerf.sh时报错：
| Unknow hparams:  []
Traceback (most recent call last):
  File "inference/nerfs/lm3d_nerf_infer.py", line 148, in <module>
    LM3dNeRFInfer.example_run(inp)
  File "/home/GeneFace/inference/nerfs/base_nerf_infer.py", line 275, in example_run
    set_hparams()
  File "/home/GeneFace/utils/commons/hparams.py", line 102, in set_hparams
    if v in ['True', 'False'] or type(config_node[k]) in [bool, list, dict]:
KeyError: 'n_samples_per_ray'
想请问一下这里是出了什么问题？
感谢

**Comment by yerfor** [comment]
你好，可能是因为你load的.yaml文件里面没有n_samples_per_ray。这还挺奇怪的。请检查一下调用的config文件是否存在。

或许你可以pull一下最新的代码。
