### ISSUE TITLE
Something wrong in data_process.sh

### ISSUE THREAD

**Issue by NoHateAnymore** [yerfor/GeneFace#8]
Thank you for your CONTRIBUTION!!!

I encountered an Error when i ran "CUDA_VISIBLE_DEVICES=0 data_gen/nerf/process_data.sh $VIDEO_ID":

……
processed parsing 5800
processed parsing 5900
processed parsing 6000
--- Step 4: extract background image ---
1400 2.6689155101776123 -7.109971523284912
1500 2.680889129638672 -7.723774433135986
1600 2.6866374015808105 -8.287768363952637
find best focal 1400
2.7772014141082764 -7.718302249908447
Traceback (most recent call last):
  File "data_util/face_tracking/face_tracker.py", line 219, in <module>
    render_imgs = renderer(rott_geo.to(device_render),
  File "/home/gammalab/anaconda3/envs/geneface/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gammalab/CS/TalkingHeadGeneration/GeneFace/data_util/face_tracking/render_3dmm.py", line 189, in forward
    rendered_img = self.renderer(mesh)
  File "/home/gammalab/anaconda3/envs/geneface/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gammalab/anaconda3/envs/geneface/lib/python3.8/site-packages/pytorch3d/renderer/mesh/renderer.py", line 56, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/home/gammalab/anaconda3/envs/geneface/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/gammalab/CS/TalkingHeadGeneration/GeneFace/data_util/face_tracking/render_3dmm.py", line 74, in forward
    images = softmax_rgb_blend(
  File "/home/gammalab/anaconda3/envs/geneface/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 188, in softmax_rgb_blend
    z_inv = (zfar - fragments.zbuf) / (zfar - znear) * mask
RuntimeError: The size of tensor a (50) must match the size of tensor b (2) at non-singleton dimension 3

**Comment by yerfor** [comment]
Hello,

I have not encountered this bug yet. It seems something gets wrong when executing the `step 6` in `process_data.sh`, in which the code tries to extract 3D head poses from each video frame. Maybe you can try two ways: 
- Try processing another video such as `May.mp4`, to figure out whether it is the problem raised by your own target video.
- If so, it might be something wrong (such as in some frames the head is missing, or hard to calculate the head pose) with your target video, and you need to process it with an external video editor (such as Adobe Premiere).

I will stay tuned for this issue. And if there are any new findings, please let me know!

**Comment by NoHateAnymore** [comment]
> Hello,
> 
> I have not encountered this bug yet. It seems something gets wrong when executing the `step 6` in `process_data.sh`, in which the code tries to extract 3D head poses from each video frame. Maybe you can try two ways:
> 
> * Try processing another video such as `May.mp4`, to figure out whether it is the problem raised by your own target video.
> * If so, it might be something wrong (such as in some frames the head is missing, or hard to calculate the head pose) with your target video, and you need to process it with an external video editor (such as Adobe Premiere).
> 
> I will stay tuned for this issue. And if there are any new findings, please let me know!

I find this error always happening after "find best focal 1400", I'm going to check details about this.

**Comment by NoHateAnymore** [comment]
Maybe this problem is caused by pytorch3d. My pytorch3d version is 0.4.0, it would lead to this error, and it can be solved with version 0.6.2.

Or solution can be found in https://github.com/facebookresearch/pytorch3d/issues/652

**Comment by yerfor** [comment]
Thanks for pointing out that, I will update this pytorch3d version requirement in the next commit.
