### ISSUE TITLE
我想用自己做的视频训练，但是在生成 aud_hubert.npy 时出现了问题。

### ISSUE THREAD

**Issue by LinGuan0624** [yerfor/GeneFace#80]
我用样例视频进行process_data是没有问题的，但当我使用自己制作的视频时，却在生成 aud_hubert.npy 时出了问题。

**具体报错信息为：**
Traceback (most recent call last):
  File "/home/aix/.conda/envs/geneface/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/aix/lg/git_project/GeneFace/data_gen/process_lrs3/process_audio_hubert.py", line 53, in get_hubert_from_16k_speech
    hidden_states = hubert_model(input_values).last_hidden_state # [B=1, T=pts//320, hid=1024]
  File "/home/aix/.conda/envs/geneface/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aix/.conda/envs/geneface/lib/python3.9/site-packages/transformers/models/hubert/modeling_hubert.py", line 1064, in forward
    extract_features = self.feature_extractor(input_values)
  File "/home/aix/.conda/envs/geneface/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aix/.conda/envs/geneface/lib/python3.9/site-packages/transformers/models/hubert/modeling_hubert.py", line 358, in forward
    hidden_states = conv_layer(hidden_states)
  File "/home/aix/.conda/envs/geneface/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aix/.conda/envs/geneface/lib/python3.9/site-packages/transformers/models/hubert/modeling_hubert.py", line 228, in forward
    hidden_states = self.conv(hidden_states)
  File "/home/aix/.conda/envs/geneface/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aix/.conda/envs/geneface/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 307, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/aix/.conda/envs/geneface/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 303, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (1). Kernel size: (3). Kernel size can't be greater than actual input size

**我debug发现，是process_audio_hubert.py 中的53行出错：**

 hidden_states = hubert_model(input_values).last_hidden_state

**这里主要原因是音频的原因，但我不知道怎么修改！**
**报错的音频是中文的，频率是标准的16khz，音频也是用 data_util/process.py 从视频中抽取出来的，我不知道为什么会报错，请问大佬们知道是怎么回事吗？**

**Comment by yerfor** [comment]
你好，报错显示

(3). Kernel size can't be greater than actual input size

这通常是因为音频过短，提取出来的input vector的长度小于网络所能接受的最小长度导致的。你可以试试换一个长一点的音频

**Comment by yerfor** [comment]
因为我们是把长音频分batch处理，有可能是因为最后一个batch的input长度小于神经网络的最小长度。或许通过把不够长的最后一batch进行zero pad就可以解决这个问题。感谢你的指出，有空时我会修复一下这个bug

**Comment by yerfor** [comment]
你好，在[这个commit](https://github.com/yerfor/GeneFace/commit/7023cf6f5a5065610f6df256962f24724c8149c8)中我们应该修复了这个bug，请你有空pull下代码后，检查一下是否能够解决你的问题。

**Comment by yerfor** [comment]
你好，在[这个commit](https://github.com/yerfor/GeneFace/commit/7023cf6f5a5065610f6df256962f24724c8149c8)中我们应该修复了这个bug，请你有空pull下代码后，检查一下是否能够解决你的问题。

**Comment by LinGuan0624** [comment]
> 

非常感谢您的及时修复，我已经把之前不能通过的音频都进行了测试，发现所有音频都能正常生成aud_hubert.npy了，不过最后一个batch的input长度如果小于kernel就直接跳过的话，会不会导致一些信息丢失？
