### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by IMISGXL** [yerfor/GeneFace#90]
安装好环境后，运行deep_3drecon/test.py 报错：RuntimeError: Not compiled with GPU support

**Comment by IMISGXL** [comment]
平台windows，显卡比较差1050ti(4g)，cuda:11.1
cudatoolkit              11.1.1              heb2d755_10    conda-forge
nvidiacub                1.9.10-1
pytorch                   1.8.0           py3.9_cuda11.1_cudnn8_0    pytorch
pytorch3d                0.7.0           pypi_0    pypi
tensorflow-gpu       2.6.0                    pypi_0    pypi

**Comment by IMISGXL** [comment]
报错具体信息：
model [FaceReconModel] was created
loading the model from ./deep_3drecon/checkpoints\facerecon\epoch_20.pth
0 deep_3drecon/datasets/examples\000002.jpg
create rasterizer on device cuda:0
Traceback (most recent call last):
  File "C:\Users\asus\Desktop\GeneFace-main\GeneFace-main\deep_3drecon\test.py", line 66, in <module>
    main(0, opt, 'deep_3drecon/datasets/examples')
  File "C:\Users\asus\Desktop\GeneFace-main\GeneFace-main\deep_3drecon\test.py", line 56, in main
    model.test()           # run inference
  File "C:\Users\asus\Desktop\GeneFace-main\GeneFace-main\deep_3drecon\deep_3drecon_models\base_model.py", line 162, in test
    self.forward()
  File "C:\Users\asus\Desktop\GeneFace-main\GeneFace-main\deep_3drecon\deep_3drecon_models\facerecon_model.py", line 139, in forward
    self.pred_mask, _, self.pred_face = self.renderer(
  File "D:\Anaconda\envs\geneface\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\asus\Desktop\GeneFace-main\GeneFace-main\deep_3drecon\util\mesh_renderer.py", line 105, in forward
    fragments = self.rasterizer(mesh, cameras = cameras, raster_settings = raster_settings)
  File "D:\Anaconda\envs\geneface\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\geneface\lib\site-packages\pytorch3d-0.7.0-py3.9-win-amd64.egg\pytorch3d\renderer\mesh\rasterizer.py", line 247, in forward
    pix_to_face, zbuf, bary_coords, dists = rasterize_meshes(
  File "D:\Anaconda\envs\geneface\lib\site-packages\pytorch3d-0.7.0-py3.9-win-amd64.egg\pytorch3d\renderer\mesh\rasterize_meshes.py", line 224, in rasterize_meshes
    pix_to_face, zbuf, barycentric_coords, dists = _RasterizeFaceVerts.apply(
  File "D:\Anaconda\envs\geneface\lib\site-packages\pytorch3d-0.7.0-py3.9-win-amd64.egg\pytorch3d\renderer\mesh\rasterize_meshes.py", line 298, in forward
    pix_to_face, zbuf, barycentric_coords, dists = _C.rasterize_meshes(
RuntimeError: Not compiled with GPU support

**Comment by IMISGXL** [comment]
pytorch是可以调用gpu：
![image](https://user-images.githubusercontent.com/56108184/230081214-76dac369-d097-475b-9382-9959c5dd5e6b.png)
tensorflow也是可以调用gpu：
![image](https://user-images.githubusercontent.com/56108184/230082027-0474f0c9-2b8f-47ab-9fc9-8e3dbfb3e1cd.png)

**Comment by yerfor** [comment]
你好，看起来是pytorch3d未被正常安装，我没试过10系列的显卡，你可以去看一下pytorch3d的官方安装文档
