### ISSUE TITLE
训练RAD-NeRF出错

### ISSUE THREAD

**Issue by LinGuan0624** [yerfor/GeneFace#92]
我在使用一个20分钟的自制视频训练RAD-NeRF时出现了错误。
**具体报错为：**
Traceback (most recent call last):
  File "/sciai/lg/project/GeneFace/tasks/run.py", line 19, in <module>
    run_task()
  File "/sciai/lg/project/GeneFace/tasks/run.py", line 14, in run_task
    task_cls.start()
  File "/sciai/lg/project/GeneFace/utils/commons/base_task.py", line 251, in start
    trainer.fit(cls)
  File "/sciai/lg/project/GeneFace/utils/commons/trainer.py", line 122, in fit
    self.run_single_process(self.task)
  File "/sciai/lg/project/GeneFace/utils/commons/trainer.py", line 186, in run_single_process
    self.train()
  File "/sciai/lg/project/GeneFace/utils/commons/trainer.py", line 286, in train
    pbar_metrics, tb_metrics = self.run_training_batch(batch_idx, batch)
  File "/sciai/lg/project/GeneFace/utils/commons/trainer.py", line 333, in run_training_batch
    output = task_ref.training_step(*args)
  File "/sciai/lg/project/GeneFace/utils/commons/base_task.py", line 109, in training_step
    loss_ret = self._training_step(sample, batch_idx, optimizer_idx)
  File "/sciai/lg/project/GeneFace/tasks/radnerfs/radnerf.py", line 194, in _training_step
    loss_output, model_out = self.run_model(sample)
  File "/sciai/lg/project/GeneFace/tasks/radnerfs/radnerf.py", line 133, in run_model
    model_out = self.model.render(rays_o, rays_d, cond_inp, bg_coords, poses, index=idx, staged=False, bg_color=bg_color, perturb=True, force_all_rays=False, **hparams)
  File "/sciai/lg/project/GeneFace/modules/radnerfs/renderer.py", line 289, in render
    ind_code = self.individual_embeddings[index]
**IndexError: index 24339 is out of bounds for dimension 0 with size 13000**

我检查/egs/egs_bases/radnerf/base.yaml时发现里面有一个参数**individual_embedding_num: 13000**，是不是这里的原因？

**Comment by Gpwner** [comment]
训练视频总帧数保持在13k内可以解决

**Comment by yerfor** [comment]
你好，你可以增大这个参数，只要大于等于你的视频总帧数即可。对性能无大影响。

**Comment by muximuxi** [comment]
> 你好，你可以增大这个参数，只要大于等于你的视频总帧数即可。对性能无大影响。

请问这个参数在哪里设置？
